// Cladding · scan · intent-onboarding (v0.3.43, F-56abaa)
//
// Intent-aware init: 사용자가 던진 짧은 의도와 환경 관찰을 결합해
// LLM 으로 4-section 고품질 onboarding 산출물을 만든다. 사용자가 명시한
// 것 이상의 도메인 베스트프랙티스까지 추론 — payment → idempotency,
// webhook signing, ledger; ML pipeline → data lineage, eval harness.
//
// Result shape:
//   - mode: greenfield | existing-adoption | mixed
//   - projectContextMd: docs/project-context.md body
//   - capabilitiesYaml: spec/capabilities.yaml body
//   - architectureYaml: spec/architecture.yaml body
//   - specSeedTitle: F-001 title (CLI 가 spec.yaml seed 에 적용)
//   - clarifyingQuestions: 다음 사이클의 Q&A 루프 seeded
//
// conventions.md 는 본 모듈에서 안 만듦 — toolchain 디폴트가 도메인
// 무관하므로 src/cli/scan/greenfield-seeds.ts 의 renderer 를 init 이
// 직접 호출.
//
// Fallback 매트릭스:
//   - dispatcher === null: deterministic 폴백 (project-context = 의도 quote, 나머지는 greenfield seeds)
//   - LLM throw: 동일 폴백 + sentinel_miss 이벤트 (phase: 'onboarding', cause: 'dispatcher_error')
//   - sentinel-miss (PROJECT_CONTEXT_MD 또는 CAPABILITIES_YAML 빈)
//     : 부분 폴백 (해당 산출물만 deterministic) + sentinel_miss 이벤트
//
// @see src/cli/scan/llm.ts — 4-sentinel buildPrompt 패턴 재사용
// @see src/cli/scan/greenfield-seeds.ts — 폴백시 토대

import {appendEvent, newEvent} from '../../events/log.js';
import {
  renderGreenfieldArchitectureYaml,
  renderGreenfieldCapabilitiesYaml,
} from './greenfield-seeds.js';
import type {ScanLlmDispatcher} from './llm.js';

/** Observed environment fed into the LLM prompt alongside the intent. */
export interface OnboardingObserved {
  /** `basename(resolve(cwd))` — small but useful hint about user's working directory. */
  readonly cwdBasename: string;
  /** Detected toolchain language ('typescript' | 'python' | 'go' | ... | 'unknown'). */
  readonly language: string;
  /** Source files seen by `scanRoot` (0 on a brand-new project). */
  readonly sourceFileCount: number;
  /** Whether a README.md (or variant) is present. */
  readonly readmePresent: boolean;
  /** First non-decorative paragraph of the README, if present. */
  readonly readmeFirstParagraph: string | null;
  /** Project display name used in titles + seed bodies. */
  readonly projectName: string;
}

/** Structured artifacts produced by an onboarding pass. */
export interface OnboardingResult {
  /** Identifies which path the LLM saw the project as. */
  readonly mode: 'greenfield' | 'existing-adoption' | 'mixed';
  /** Full body for `docs/project-context.md` — Why/What/Purpose. */
  readonly projectContextMd: string;
  /** Full body for `spec/capabilities.yaml`. */
  readonly capabilitiesYaml: string;
  /** Full body for `spec/architecture.yaml`. */
  readonly architectureYaml: string;
  /** Suggested title for the placeholder F-001 in `spec.yaml`. */
  readonly specSeedTitle: string;
  /** 2-3 product/business-level questions the orchestrator can ask next. */
  readonly clarifyingQuestions: readonly string[];
  /** llm | deterministic | hybrid (per-section fallback). */
  readonly source: 'llm' | 'deterministic' | 'hybrid';
}

const ONBOARDING_HEADER =
  '<!-- Auto-generated by `clad init <intent>`. Onboarding refined from ' +
  'user intent + environment observation. Edit freely — re-running ' +
  '`clad init <new-intent>` diverts the new body to ' +
  '`.cladding/scan/project-context.md.proposal` for review. -->';

const DETERMINISTIC_HEADER =
  '<!-- Auto-generated by `clad init <intent>`. LLM unavailable or ' +
  'response sentinel-miss; the body below is a deterministic fallback ' +
  'that quotes your intent verbatim. Re-run with a connected LLM ' +
  'dispatcher to capture domain context. -->';

/**
 * Builds the LLM prompt asking for 6 sentinel-labelled sections that
 * together produce the four onboarding artifacts. The prompt is
 * deliberately written in *senior architect* tone — the LLM is told
 * to produce output that exceeds the user's literal request.
 *
 * The CLARIFYING_QUESTIONS section is guard-railed at the prompt level:
 * the LLM MUST ask product/business questions, not implementation
 * choices, and MUST match vocabulary to the user's intent.
 */
export function buildOnboardingPrompt(
  intent: string,
  observed: OnboardingObserved,
): string {
  const readmePara = observed.readmeFirstParagraph
    ? `"${observed.readmeFirstParagraph}"`
    : '(none observed)';
  return [
    'You are a senior software architect setting up a new project workspace',
    'via cladding. The user gave a short description; your job is to produce',
    'artifacts that REPRESENT THE PROJECT BETTER THAN THE USER EXPLICITLY STATED.',
    '',
    `User intent: "${intent}"`,
    '',
    'Observed environment:',
    `- Project name (cwd basename): ${observed.projectName}`,
    `- Detected language: ${observed.language}`,
    `- Existing source files: ${observed.sourceFileCount}`,
    `- README present: ${observed.readmePresent ? 'yes' : 'no'}`,
    `- README first paragraph: ${readmePara}`,
    '',
    'For the user\'s intent, identify the domain and produce 6 sentinel sections.',
    'Use the EXACT sentinel strings below so the response is parsable.',
    '',
    '=== ONBOARDING_MODE ===',
    'One word: greenfield | existing-adoption | mixed. Choose based on',
    'whether the intent text + observed files indicate a brand-new project',
    '(greenfield), an adoption of cladding into an existing codebase',
    '(existing-adoption), or a hybrid (greenfield code + intent that names',
    'an existing project).',
    '',
    '=== PROJECT_CONTEXT_MD ===',
    `Full body for docs/project-context.md. Use markdown headings.`,
    'Capture BOTH the user\'s stated intent AND inferred domain context',
    '(compliance norms, scale assumptions, common architectural patterns).',
    'Three subsections: "## 1. Why does this project exist?", "## 2. What',
    'problem does it solve?", "## 3. What is its purpose?". Be specific.',
    'Avoid generic phrases ("modern", "powerful", "robust").',
    '',
    '=== CAPABILITIES_YAML ===',
    'Full body for spec/capabilities.yaml. Schema:',
    '  schema: "0.1"',
    '  source: intent (greenfield) | README.md (existing-adoption)',
    '  capabilities:',
    '    - id: <kebab-slug>',
    '      title: "<verbatim or inferred capability name>"',
    '      summary: "<one sentence>"',
    '      surface: feature | platform | tool | infrastructure',
    'Mix user-stated capabilities (preserve names verbatim when they used',
    'specific terms) with domain best-practice inferred capabilities.',
    'Aim for 3-8 entries total. Inferred entries should be ones the user',
    'would forget to mention but the domain expects (e.g., payment →',
    'idempotency, webhook signing, audit trail; ML pipeline → data',
    'lineage, eval harness; SaaS → multi-tenancy, audit log).',
    '',
    '=== ARCHITECTURE_YAML ===',
    'Full body for spec/architecture.yaml. Schema:',
    '  version: "0.1"',
    '  layers: [{name, modules:[<glob>], forbidden_imports:[<layer>]}, ...]',
    'Tailor layers to the domain + language. Add a 1-line comment per',
    'layer summarising its responsibility. Add forbidden_imports',
    'candidates matching the domain\'s typical isolation rules.',
    '',
    '=== SPEC_SEED_TITLE ===',
    'A single short line: the natural first feature for this kind of',
    'project. NOT a placeholder — pick something the user would actually',
    'build first (e.g., payment SaaS → "결제 인증 흐름"; ML pipeline →',
    '"데이터 수집 파이프라인"; marketing site → "랜딩 페이지 렌더링").',
    'Match the user\'s language (Korean intent → Korean title).',
    '',
    '=== CLARIFYING_QUESTIONS ===',
    '2-3 PRODUCT/BUSINESS-level questions to ask the user next, one per',
    'line. RULES (mandatory):',
    '- Ask GOAL / AUDIENCE / SCOPE questions, not implementation choices.',
    '- Match vocabulary to what the user used in their intent.',
    '  - Casual intent ("결제 SaaS", "쇼핑몰") → plain-language questions.',
    '  - Technical intent ("PCI-DSS gateway") → deeper questions OK.',
    '- Each question must be answerable by a product owner without research.',
    '- NEVER ask about technical jargon the user did not bring up first.',
    '',
    'BAD examples (intimidating, expert-only):',
    '  "PCI-DSS SAQ A vs SAQ D?"',
    '  "Webhook idempotency — single-flight or distributed lock?"',
    '  "SSR vs SSG vs ISR?"',
    '',
    'GOOD examples (product/business level):',
    '  payment SaaS: "주 사용자가 개인? 사업자?", "어떤 결제수단 우선?",',
    '                "한국 시장 위주? 글로벌?"',
    '  ML pipeline: "사용자가 실시간 결과 기다리나? 배치 OK?",',
    '               "어떤 데이터로 학습? 공개 vs 자체수집?"',
    '  shopping mall: "재고 실시간 정확성 중요? 약간 느려도 OK?",',
    '                 "어떤 결제수단 / 배송 방식?"',
    '',
    'CRITICAL: aim for *informed* output, not safe output. A short intent',
    'deserves a richly-inferred scaffold. The user can edit anything; they',
    'cannot add what you did not suggest. Questions, however, MUST stay',
    'at the level the user can actually answer.',
  ].join('\n');
}

/** Splits the LLM response into the six labelled sections. */
export function parseOnboardingResponse(text: string): {
  readonly mode: string;
  readonly projectContext: string;
  readonly capabilities: string;
  readonly architecture: string;
  readonly specSeedTitle: string;
  readonly clarifyingQuestionsRaw: string;
} {
  return {
    mode: extractSection(text, 'ONBOARDING_MODE'),
    projectContext: extractSection(text, 'PROJECT_CONTEXT_MD'),
    capabilities: extractSection(text, 'CAPABILITIES_YAML'),
    architecture: extractSection(text, 'ARCHITECTURE_YAML'),
    specSeedTitle: extractSection(text, 'SPEC_SEED_TITLE'),
    clarifyingQuestionsRaw: extractSection(text, 'CLARIFYING_QUESTIONS'),
  };
}

function extractSection(text: string, name: string): string {
  const re = new RegExp(`=== ${name} ===([\\s\\S]*?)(?:===\\s*[A-Z_]+\\s*===|$)`);
  const m = text.match(re);
  return m ? m[1].trim() : '';
}

/**
 * Parses the raw `CLARIFYING_QUESTIONS` block into a list of questions.
 * Accepts bullets ("- ", "* ", "1. ") or plain lines. Filters empty
 * lines. Caps at 5 to keep the CLI hint compact.
 */
export function extractClarifyingQuestions(raw: string): readonly string[] {
  if (!raw.trim()) return [];
  return raw
    .split('\n')
    .map((line) => line.replace(/^\s*(?:[-*]|\d+[.)])\s*/, '').trim())
    .filter((line) => line.length > 0)
    .slice(0, 5);
}

/**
 * Normalises the LLM's `ONBOARDING_MODE` to one of the three allowed
 * values. Defaults to `greenfield` when the LLM returned something
 * unexpected, since the caller can always re-run with `--scan` to
 * force the observed path.
 */
export function normaliseMode(raw: string): OnboardingResult['mode'] {
  const cleaned = raw.toLowerCase().trim();
  if (cleaned.includes('existing')) return 'existing-adoption';
  if (cleaned.includes('mixed')) return 'mixed';
  return 'greenfield';
}

/**
 * Top-level orchestration. Calls the LLM (if available), parses the
 * response, fills any blank sentinels with deterministic fallbacks,
 * and emits `sentinel_miss` events for telemetry parity with the
 * existing scan pipeline.
 *
 * The optional `cwd` is the workspace root used for event emission —
 * tests that call this helper without a workspace omit it to stay
 * telemetry-silent (mirrors `interpretScanWithFallback` in llm.ts).
 */
export async function interpretOnboardingWithFallback(
  intent: string,
  observed: OnboardingObserved,
  dispatcher: ScanLlmDispatcher | null,
  cwd?: string,
): Promise<OnboardingResult> {
  if (dispatcher === null) {
    return deterministicOnboarding(intent, observed);
  }
  let raw: string;
  try {
    raw = await dispatcher(buildOnboardingPrompt(intent, observed));
  } catch (e) {
    emitSentinelMiss(cwd, {
      phase: 'onboarding',
      cause: 'dispatcher_error',
      fallback: 'total',
      error: truncateError(e),
    });
    return deterministicOnboarding(intent, observed);
  }
  const parsed = parseOnboardingResponse(raw);
  const missed: string[] = [];
  if (!parsed.projectContext.trim()) missed.push('PROJECT_CONTEXT_MD');
  if (!parsed.capabilities.trim()) missed.push('CAPABILITIES_YAML');
  if (!parsed.architecture.trim()) missed.push('ARCHITECTURE_YAML');
  if (!parsed.specSeedTitle.trim()) missed.push('SPEC_SEED_TITLE');
  // CLARIFYING_QUESTIONS is allowed to be empty — not all intents
  // need a follow-up. Mode is normalised, so a blank value still
  // resolves to greenfield.

  // Critical sentinel-miss: project-context + capabilities both blank
  // → total fallback. Otherwise per-section fallback (keeps mode=hybrid).
  const total =
    missed.includes('PROJECT_CONTEXT_MD') &&
    missed.includes('CAPABILITIES_YAML') &&
    missed.includes('ARCHITECTURE_YAML');
  if (total) {
    emitSentinelMiss(cwd, {
      phase: 'onboarding',
      cause: 'blank_section',
      fallback: 'total',
      missed_sections: missed,
    });
    return deterministicOnboarding(intent, observed);
  }
  if (missed.length > 0) {
    emitSentinelMiss(cwd, {
      phase: 'onboarding',
      cause: 'blank_section',
      fallback: 'per_artifact',
      missed_sections: missed,
    });
  }

  const mode = normaliseMode(parsed.mode);
  return {
    mode,
    projectContextMd: parsed.projectContext.trim()
      ? wrapProjectContext(parsed.projectContext, observed.projectName, ONBOARDING_HEADER)
      : deterministicProjectContext(intent, observed),
    capabilitiesYaml: parsed.capabilities.trim()
      ? ensureTrailingNewline(parsed.capabilities)
      : renderGreenfieldCapabilitiesYaml(observed.projectName),
    architectureYaml: parsed.architecture.trim()
      ? ensureTrailingNewline(parsed.architecture)
      : renderGreenfieldArchitectureYaml(observed.language),
    specSeedTitle: parsed.specSeedTitle.trim() || deterministicSeedTitle(intent),
    clarifyingQuestions: extractClarifyingQuestions(parsed.clarifyingQuestionsRaw),
    source: missed.length === 0 ? 'llm' : 'hybrid',
  };
}

/**
 * Deterministic fallback used when the LLM is unavailable or the
 * response is unusable. Produces a complete OnboardingResult so the
 * caller can still write artifacts and surface intent context.
 */
/**
 * Deterministic fallback. The caller passes the reason via the
 * `sentinel_miss` event payload (in `interpretOnboardingWithFallback`)
 * rather than through this signature — that keeps the function pure
 * and easy to test, while still surfacing the reason in telemetry.
 */
export function deterministicOnboarding(
  intent: string,
  observed: OnboardingObserved,
): OnboardingResult {
  return {
    mode: observed.sourceFileCount >= 3 ? 'existing-adoption' : 'greenfield',
    projectContextMd: deterministicProjectContext(intent, observed),
    capabilitiesYaml: renderGreenfieldCapabilitiesYaml(observed.projectName),
    architectureYaml: renderGreenfieldArchitectureYaml(observed.language),
    specSeedTitle: deterministicSeedTitle(intent),
    // Deterministic mode has no clarifying questions — the LLM was the
    // source of question calibration; without it we cannot guarantee
    // question quality.
    clarifyingQuestions: [],
    source: 'deterministic',
  };
}

function deterministicProjectContext(intent: string, observed: OnboardingObserved): string {
  const lines: string[] = [
    DETERMINISTIC_HEADER,
    '',
    `# ${observed.projectName} — Project Context`,
    '',
    '## 1. Why does this project exist?',
    '',
    `_User intent (verbatim)_: ${intent}`,
    '',
    'The LLM dispatcher was unavailable or returned an unusable response,',
    'so this section quotes your intent without inferred domain context.',
    'Re-run `clad init <intent>` once a dispatcher is connected to get a',
    'refined Why/What/Purpose write-up.',
    '',
    '## 2. What problem does it solve?',
    '',
    '_Refine by hand or re-run with LLM available._',
    '',
    '## 3. What is its purpose?',
    '',
    '_Refine by hand or re-run with LLM available._',
    '',
    '## See also',
    '',
    '- `docs/conventions.md` — observed code conventions',
    '- `spec/architecture.yaml` — observed layers',
    '- `spec/capabilities.yaml` — README-derived capability inventory',
    '- `spec.yaml` — feature registry',
    '',
  ];
  return lines.join('\n');
}

function deterministicSeedTitle(intent: string): string {
  const trimmed = intent.trim();
  if (trimmed.length === 0) return 'Your first feature';
  // Use the first ~60 chars of the intent as the title.
  const cut = trimmed.length > 60 ? `${trimmed.slice(0, 57)}…` : trimmed;
  return cut;
}

function wrapProjectContext(body: string, projectName: string, header: string): string {
  // If the LLM-produced body already starts with a heading or
  // comment, prepend just the header. Otherwise add a title line.
  const trimmed = body.trim();
  const hasTitle = trimmed.startsWith('# ') || trimmed.startsWith('<!--');
  const titleLine = hasTitle ? '' : `# ${projectName} — Project Context\n\n`;
  return `${header}\n\n${titleLine}${trimmed}\n`;
}

function ensureTrailingNewline(text: string): string {
  return text.endsWith('\n') ? text : `${text}\n`;
}

function emitSentinelMiss(cwd: string | undefined, payload: Record<string, unknown>): void {
  if (!cwd) return;
  try {
    appendEvent(cwd, newEvent('sentinel_miss', payload));
  } catch {
    // Telemetry must never break init.
  }
}

function truncateError(e: unknown): string {
  const msg = e instanceof Error ? e.message : String(e);
  return msg.length > 200 ? `${msg.slice(0, 200)}…` : msg;
}
