// Cladding · `clad init --scan` — LLM interpretation layer
//
// Takes the deterministic {@link ScanResult} from scan.ts and produces
// the human-readable `docs/conventions.md` + `spec/architecture.yaml` +
// per-scenario `flow` text that downstream specialist agents consume.
//
// The LLM call is abstracted as an injectable dispatcher so this module
// stays unit-testable without the MCP sampling stack. The production
// dispatcher (v0.3.25) will route through `src/adapters/host/sampling-
// context.ts` once it lands; v0.3.24 ships the contract + the
// {@link deterministicInterpret} fallback so `--no-llm` runs (and CI
// invocations without a sampling-capable host) still produce valid
// artifacts — just less polished prose.
//
// @see ironclad-design/07-ssot-init.md §3 B
// @see scan.ts — deterministic data source
// @see src/adapters/host/sampling-context.ts — dispatcher candidate

import type {ProjectContext, ScanResult, Conventions, Layer} from './types.js';

/** Single-prompt dispatcher injected by callers. */
export type ScanLlmDispatcher = (prompt: string) => Promise<string>;

/** Interpreted artifacts ready for file write. */
export interface InterpretedScan {
  /** Final `docs/conventions.md` body. Includes the auto-generated header. */
  readonly conventionsMd: string;
  /** Final `spec/architecture.yaml` body, schema-conformant. */
  readonly architectureYaml: string;
  /** Per-scenario `flow` text keyed by scenario slug. */
  readonly scenarioFlows: ReadonlyMap<string, string>;
  /** Identifies how the artifacts were produced — surfaces in commit notes. */
  readonly mode: 'llm' | 'deterministic';
}

const HEADER =
  '<!-- Auto-generated by `clad init --scan`. Observed conventions — review and edit. -->';

/**
 * Packs the deterministic scan data into a single prompt the LLM can
 * turn into prose. The prompt asks for three labelled sections so
 * {@link parseLlmResponse} can split them by sentinel rather than
 * trying to parse free-form markdown.
 */
export function buildPrompt(scan: ScanResult): string {
  const conv = scan.conventions;
  const examples = scan.examples
    .map(
      (e) =>
        `### ${e.layer} — ${e.modulePath}\n\n\`\`\`\n${e.moduleContent}\n\`\`\`` +
        (e.testContent ? `\n\n### ${e.layer} test — ${e.testPath}\n\n\`\`\`\n${e.testContent}\n\`\`\`` : ''),
    )
    .join('\n\n');
  const layers = scan.architecture.layers.map((l) => `- ${l.name} (${l.moduleCount} modules)`).join('\n');
  const importEdges = scan.architecture.importGraph
    .slice(0, 20)
    .map((e) => `- ${e.from} → ${e.to} (${e.count})`)
    .join('\n');
  return [
    'You are the librarian agent of a project that just adopted cladding.',
    'Three deliverables. Use the exact sentinels below so output is parsable.',
    '',
    '=== CONVENTIONS_MD ===',
    'Write a docs/conventions.md body documenting observed conventions',
    'plus a "Adding a new module" section that lets a future AI maintain',
    'this project in the same shape. Be concrete and quote the example.',
    '',
    '=== ARCHITECTURE_YAML ===',
    'Write spec/architecture.yaml. Schema:',
    '  version: "0.1"',
    '  layers: [{name, modules:[<glob>], forbidden_imports:[<layer>]}, ...]',
    'Use the observed import graph to infer forbidden_imports (pairs',
    'never seen in the graph become candidates). Add a 1-line comment',
    'per layer summarising its responsibility.',
    '',
    '=== SCENARIO_FLOWS ===',
    'For each layer below, write one or two sentences describing the',
    'business flow that layer enables. Format: `<slug>: <prose>`.',
    '',
    '--- Observed conventions ---',
    JSON.stringify(conv, null, 2),
    '',
    '--- Layers ---',
    layers,
    '',
    '--- Import graph (top 20) ---',
    importEdges,
    '',
    '--- Example modules ---',
    examples,
  ].join('\n');
}

/**
 * Splits the LLM response into the three labelled sections. Returns
 * the parts verbatim; callers prepend the header and final wrapping.
 */
export function parseLlmResponse(text: string): {
  readonly conventions: string;
  readonly architecture: string;
  readonly scenarios: string;
} {
  const conv = extractSection(text, 'CONVENTIONS_MD');
  const arch = extractSection(text, 'ARCHITECTURE_YAML');
  const scen = extractSection(text, 'SCENARIO_FLOWS');
  return {conventions: conv, architecture: arch, scenarios: scen};
}

function extractSection(text: string, name: string): string {
  const re = new RegExp(`=== ${name} ===([\\s\\S]*?)(?:===\\s*[A-Z_]+\\s*===|$)`);
  const m = text.match(re);
  return m ? m[1].trim() : '';
}

/**
 * Runs the LLM path: prompts, parses, and assembles the InterpretedScan.
 * Errors (transport, parse) flow up to the caller — fallback to
 * deterministic mode is the caller's policy decision, not this
 * function's.
 */
export async function interpretWithLlm(
  scan: ScanResult,
  dispatch: ScanLlmDispatcher,
): Promise<InterpretedScan> {
  const prompt = buildPrompt(scan);
  const raw = await dispatch(prompt);
  const sections = parseLlmResponse(raw);
  const scenarioFlows = new Map<string, string>();
  for (const line of sections.scenarios.split('\n')) {
    const m = line.match(/^([\w-]+):\s+(.+)$/);
    if (m) scenarioFlows.set(m[1], m[2]);
  }
  return {
    conventionsMd: `${HEADER}\n\n${sections.conventions}`,
    architectureYaml: sections.architecture,
    scenarioFlows,
    mode: 'llm',
  };
}

/**
 * `--no-llm` fallback. Builds artifacts straight from the scan data
 * with no LLM call. The conventions doc becomes a structured table
 * (less prose, same facts); architecture.yaml carries the observed
 * layers with placeholder responsibilities; scenario flows fall back
 * to a one-liner per layer that names the directory.
 *
 * The header explicitly notes the deterministic mode so reviewers
 * know the file lacks LLM polish.
 */
export function deterministicInterpret(scan: ScanResult): InterpretedScan {
  const conventionsMd = `${HEADER}\n\n` + renderConventionsTable(scan.conventions, scan.examples);
  const architectureYaml = renderArchitectureYaml(
    scan.architecture.layers,
    scan.architecture.forbiddenImportCandidates,
  );
  const scenarioFlows = new Map<string, string>();
  for (const s of scan.scenarios) {
    scenarioFlows.set(s.slug, `Flow through ${s.dir}/ (${s.moduleCount} modules) — describe the business behaviour this layer enables.`);
  }
  return {conventionsMd, architectureYaml, scenarioFlows, mode: 'deterministic'};
}

function renderConventionsTable(c: Conventions, examples: ScanResult['examples']): string {
  const lines: string[] = [
    '# Project conventions',
    '',
    '_Mode: deterministic (no LLM polish). Re-run `clad scan` without `--no-llm` for prose._',
    '',
    '## Observed style',
    '',
    '| key | value |',
    '|---|---|',
    `| indent | ${c.indent} |`,
    `| quote | ${c.quote} |`,
    `| semicolon | ${c.semicolon} |`,
    `| naming (exports) | ${c.namingExports} |`,
    `| naming (constants) | ${c.namingConstants} |`,
    `| docblock ratio | ${c.docBlockRatio.toFixed(2)} |`,
    `| import order | ${c.importOrder} |`,
    `| export pattern | ${c.exportPattern} |`,
    `| error handling | ${c.errorHandling} |`,
    `| type def location | ${c.typeDefLocation} |`,
    `| test location | ${c.testLocation} |`,
    `| file header | ${c.fileHeaderPattern ?? '(none)'} |`,
    '',
    '## Doc tag frequency',
    '',
  ];
  for (const [tag, count] of Object.entries(c.docTagCounts)) {
    lines.push(`- \`${tag}\`: ${count}`);
  }
  if (c.moduleBoilerplate) {
    lines.push('', '## Module boilerplate (smallest exported module observed)', '', '```', c.moduleBoilerplate, '```');
  }
  if (examples.length > 0) {
    lines.push('', '## Representative modules');
    for (const e of examples) {
      lines.push('', `### ${e.layer} · ${e.modulePath}`, '', '```', e.moduleContent, '```');
      if (e.testContent && e.testPath) {
        lines.push('', `### ${e.layer} test · ${e.testPath}`, '', '```', e.testContent, '```');
      }
    }
  }
  return lines.join('\n');
}

function renderArchitectureYaml(
  layers: readonly Layer[],
  forbiddenCandidates: Readonly<Record<string, readonly string[]>>,
): string {
  const lines: string[] = [
    'version: "0.1"',
    '# Auto-generated by `clad init --scan`. `forbidden_imports` lists',
    '# layer pairs the scan never observed in your import graph — they',
    '# are candidates, not enforced rules. Prune the list to the ones',
    '# you actually want to forbid before committing.',
    'layers:',
  ];
  for (const l of layers) {
    const candidates = forbiddenCandidates[l.name] ?? [];
    const forbiddenList = candidates.length === 0 ? '[]' : `[${candidates.map((c) => `"${c}"`).join(', ')}]`;
    lines.push(`  - name: ${l.name}`);
    lines.push(`    modules: ["${l.dir}/**"]`);
    lines.push(`    forbidden_imports: ${forbiddenList}`);
  }
  return lines.join('\n') + '\n';
}

const PROJECT_CONTEXT_HEADER =
  '<!-- Auto-generated by `clad init`. Observed when README is present, ' +
  'template otherwise. Review and edit. -->';

/**
 * Renders `docs/project-context.md` from an observed
 * {@link ProjectContext} or, when null, a fresh template. The
 * caller (init.ts) writes the result to disk and the template
 * route is what greenfield projects see.
 *
 * @param ctx Observed context, or null when no README + no docs +
 *   no source-side signatures surfaced.
 * @param projectName Used as the title heading.
 */
export function renderProjectContextMd(ctx: ProjectContext | null, projectName: string): string {
  if (ctx === null) return renderProjectContextTemplate(projectName);
  return renderProjectContextObserved(ctx, projectName);
}

function renderProjectContextTemplate(projectName: string): string {
  return [
    PROJECT_CONTEXT_HEADER,
    '',
    `# ${projectName} — Project Context`,
    '',
    'Entry document for any AI maintainer joining this codebase. Fill',
    'in the sections before requesting features so the spec stays',
    'honest about *why* the project exists.',
    '',
    '## 1. Why does this project exist?',
    '',
    '_Motivation. What gap or pain led to this project being started?_',
    '',
    '## 2. What problem does it solve?',
    '',
    '_Concrete problem statement. Who feels the pain? When?_',
    '',
    '## 3. What is its purpose?',
    '',
    '_Vision in one or two sentences. What does success look like?_',
    '',
    '## 4. Top-level capabilities',
    '',
    '_High-level functions this project provides. Sub-features register',
    'through `clad_create_feature` as work proceeds._',
    '',
    '- [ ] Capability 1 — short description',
    '- [ ] Capability 2 — short description',
    '',
    '## See also',
    '',
    '- `spec.yaml` — feature registry (grown by `clad_create_feature`)',
    '- `docs/code-style.md` — recommended code conventions for new code',
    '',
  ].join('\n');
}

function renderProjectContextObserved(ctx: ProjectContext, projectName: string): string {
  const lines: string[] = [
    PROJECT_CONTEXT_HEADER,
    '',
    `# ${projectName} — Project Context`,
    '',
  ];

  // 1. What this project is — README first paragraph (raw).
  lines.push('## 1. What this project is (observed)', '');
  if (ctx.readmeFirstParagraph) {
    lines.push(`> ${ctx.readmeFirstParagraph}`);
  } else {
    lines.push('_README first paragraph not found — please describe._');
  }
  lines.push('');

  // 2. Documented context — sibling docs inventory.
  if (ctx.docLinks.length > 0) {
    lines.push('## 2. Documented context', '');
    for (const link of ctx.docLinks) {
      lines.push(`- \`${link.path}\` — ${link.firstLine}`);
    }
    lines.push('');
  }

  // 3. Top-level sections — README headings.
  if (ctx.readmeHeadings.length > 0) {
    lines.push(
      '## 3. Top-level sections (from README headings)',
      '',
      '_Reviewer interprets as capabilities — refine into `spec/capabilities.yaml` once v0.4 lands._',
      '',
    );
    for (const h of ctx.readmeHeadings) lines.push(`- ${h}`);
    lines.push('');
  }

  // 4. Representative interfaces — TS signatures from top layers.
  if (ctx.interfaceSignatures.length > 0) {
    lines.push('## 4. Representative interfaces', '');
    for (const entry of ctx.interfaceSignatures) {
      lines.push(`### ${entry.layer}`, '', '```ts');
      for (const sig of entry.signatures) lines.push(sig);
      lines.push('```', '');
    }
  }

  // 5. Why / Purpose — review needed (LLM refinement queued).
  lines.push(
    '## 5. Why / Purpose (review needed)',
    '',
    'The scan inferred raw text from your README — please refine the',
    'Why and Purpose sections by hand. Cladding cannot guess intent',
    'from observed code alone; the LLM-assisted v0.3.33+ pass will',
    'help refine these.',
    '',
    '## See also',
    '',
    '- `docs/conventions.md` — observed code conventions',
    '- `spec/architecture.yaml` — observed layers',
    '- `spec.yaml` — feature registry',
    '',
  );
  return lines.join('\n');
}
