// Cladding · scenarios · ab-extended · shared scaffold (v0.3.52, F-ef2fd9)
//
// React 19 + Vite 6 + TS 5.6 + Tailwind 4 boilerplate templates shared
// across A/B-extended scenarios (task-manager, dashboard, future blog).
// Each scenario's curator imports these strings to avoid duplication.

import {writeFileSync, mkdirSync} from 'node:fs';
import {dirname, join} from 'node:path';

export function write(cwd: string, rel: string, body: string): void {
  const abs = join(cwd, rel);
  mkdirSync(dirname(abs), {recursive: true});
  writeFileSync(abs, body);
}

export const PACKAGE_JSON_TEMPLATE = (name: string): string => `{
  "name": "${name}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "preview": "vite preview",
    "test": "vitest run"
  },
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^6.6.0",
    "@testing-library/react": "^16.1.0",
    "@types/node": "^22.10.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "@vitejs/plugin-react": "^4.3.0",
    "jsdom": "^25.0.0",
    "tailwindcss": "^4.0.0",
    "typescript": "^5.6.0",
    "vite": "^6.0.0",
    "vitest": "^2.1.0"
  }
}
`;

export const TSCONFIG_JSON = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "jsx": "react-jsx",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true,
    "isolatedModules": true,
    "noEmit": true,
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "useDefineForClassFields": true
  },
  "include": ["src", "tests"]
}
`;

export const VITE_CONFIG = `import {defineConfig} from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./tests/_setup.ts'],
  },
});
`;

export const TAILWIND_CONFIG = `import type {Config} from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
} satisfies Config;
`;

export const INDEX_HTML = (title: string): string => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body class="bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100">
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

export const MAIN_TSX = `import {StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import './index.css';
import {App} from './App';

const root = document.getElementById('root');
if (!root) throw new Error('root element missing');

createRoot(root).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`;

export const INDEX_CSS = `@import "tailwindcss";

:root {
  --tm-accent: #2563eb;
  --tm-accent-text: #ffffff;
}

:root.dark {
  --tm-accent: #60a5fa;
}

@media (max-width: 640px) {
  .tm-container {
    padding-inline: 0.75rem;
  }
}
`;

export const TESTS_SETUP = `import '@testing-library/jest-dom/vitest';
`;

export const GITIGNORE = `node_modules/
dist/
*.log
.env
.DS_Store
`;

export const README_RUN = (scenarioName: string, group: 'cladding' | 'vanilla'): string => `# ${scenarioName} (${group})

This is the **${group}** group's React + Vite + TS + Tailwind ${scenarioName} — auto-generated by
\`tests/scenarios/ab-extended/_curator-${scenarioName}.ts\` as part of the large-scale A/B
evaluation framework.

${group === 'cladding'
  ? 'Includes the full cladding governance scaffold: `spec.yaml`, 30 `spec/features/*.yaml` shards, `spec/architecture.yaml`, `spec/capabilities.yaml`, plus `docs/project-context.md` and `docs/conventions.md`.'
  : 'No cladding scaffold — just the React app source. Vanilla developer would ship this on its own.'}

## Run locally

\`\`\`bash
cd "${'$'}{this directory}"
npm install
npm run dev    # opens at http://localhost:5173
\`\`\`

## Test

\`\`\`bash
npm test
\`\`\`

## Compare with the other group

The sibling directory \`../${group === 'cladding' ? 'vanilla' : 'cladding'}/\` ships the same React app
${group === 'cladding' ? 'without' : 'with'} cladding governance.
`;
