// Cladding · `clad init` — workspace scaffolder
//
// One command, three side-effects on a fresh directory:
//   1. spec.yaml seed with one placeholder feature (F-001)
//   2. .cladding/ runtime dir (audit + events log live here)
//   3. .gitignore append (.cladding/ entry; appended only if missing)
//
// Idempotent by default — re-running on an initialised workspace is a
// no-op except for reporting. `--force` overwrites the seed spec.yaml
// (other artifacts stay safe). Language is auto-detected from the
// manifest chain (package.json / pyproject.toml / Cargo.toml / …);
// `unknown` falls back to typescript so the seed is always valid.

import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {basename, dirname, join, resolve} from 'node:path';

import {
  interpretScanWithFallback,
  renderProjectContextMd,
  renderProjectContextMdWithLlm,
  scanRoot,
  selectDispatcher,
  type InterpretedScan,
} from './scan/index.js';
import {
  renderGreenfieldArchitectureYaml,
  renderGreenfieldCapabilitiesYaml,
  renderGreenfieldConventionsMd,
} from './scan/greenfield-seeds.js';
import {
  interpretOnboardingWithFallback,
  type OnboardingObserved,
  type OnboardingResult,
} from './scan/intent-onboarding.js';
import {saveState, type OnboardingState} from './scan/onboarding-state.js';
import {detectToolchain} from '../stages/toolchain/detect.js';
import {detectContext} from '../init/detect.js';
import {buildMarker, patchMarkerInSpec, renderMarkerYaml, type EnrichmentMarker} from '../init/marker.js';
import {writeAgentsMd, writeClaudeMdSection} from '../init/host-instructions.js';
import {getCurrentCladdingVersion, getLastSetupVersion} from '../init/host-setup.js';
import {loadIntentFromPathIfApplicable} from './intent-from-path.js';

export interface InitOptions {
  readonly cwd?: string;
  readonly projectName?: string;
  readonly force?: boolean;
  /** Walks the existing codebase and writes docs/conventions.md + spec/architecture.yaml + scenario stubs. */
  readonly scan?: boolean;
  /** Forces the deterministic-only fallback even when an LLM dispatcher is available. */
  readonly noLlm?: boolean;
  /** Source-root override for the scanner, e.g. ["packages/a/src", "packages/b/src"]. */
  readonly roots?: readonly string[];
  /**
   * Free-text user intent (v0.3.43+). When provided, init routes through
   * the LLM-driven onboarding path (`intent-onboarding.ts`) which produces
   * domain-aware seeds for project-context / capabilities / architecture
   * plus a real F-001 title and 2-3 follow-up questions. When omitted,
   * init falls back to the v0.3.42 behaviour (toolchain-default seeds in
   * greenfield, observed scan otherwise).
   */
  readonly intent?: string;
}

export interface InitResult {
  readonly created: readonly string[];
  readonly skipped: readonly string[];
  readonly language: string;
  /** Files diverted to `.cladding/scan/*.proposal.*` because an authored copy already existed. */
  readonly proposals?: readonly string[];
  /**
   * Product/business-level follow-up questions emitted by the LLM during
   * intent-aware onboarding. Empty when no intent was given or when the
   * deterministic fallback fired. The CLI surfaces these as hints.
   */
  readonly clarifyingQuestions?: readonly string[];
  /** Mode the onboarding pass classified the project as (intent path only). */
  readonly onboardingMode?: OnboardingResult['mode'];
}

// v0.3.30 — Scenarios in cladding capture *user journeys* (business
// intent), not architecture layers. Cladding writes this README at
// adoption time so reviewers understand why the directory is empty
// and how it grows.
const SCENARIOS_README = [
  '<!-- Auto-generated by `clad init --scan`. Do not author scenario YAML by hand. -->',
  '',
  '# Scenarios',
  '',
  'Scenarios in cladding capture **user journeys** — the business flows your',
  'system enables, not the architecture layers your code is organised into.',
  '',
  'You do not author scenario YAML by hand. They are auto-registered when you',
  'request a feature through `clad_create_feature` or through natural-language',
  'conversation with your AI host. The scenario your request belongs to is',
  'inferred together with the feature itself.',
  '',
  'This directory is intentionally empty at scan time. The first scenario lands',
  'when you ship the first feature.',
  '',
  '## Why not auto-extract from existing code?',
  '',
  'A user journey is *intent* — the question your codebase answers for the',
  'people who use it. Cladding could guess at intent from routers, README',
  'headings, or call graphs, but those are *architecture signals*, not journey',
  'signals. Guesses ship as authoritative YAML and mislead reviewers. Cladding',
  'instead waits for you to declare intent through a feature request and binds',
  'the scenario to that declaration.',
  '',
  '## See also',
  '',
  '- `docs/conventions.md` — observed conventions (auto-generated)',
  '- `spec/architecture.yaml` — observed layers + forbidden_imports candidates',
  '- `spec.yaml` — feature registry (grown by clad_create_feature)',
  '',
].join('\n');

/** Optional project metadata for the spec.yaml seed (F-3a5339, v0.3.49). */
interface SpecSeedMetadata {
  /** One-line summary of the project. Falls back to intent if not provided. */
  readonly description?: string;
  /** Starting project version. Default '0.0.1'. */
  readonly version?: string;
  /** Source-repository URL. Empty placeholder line when not provided. */
  readonly repository?: string;
  /** TL;DR of project-context.md. Falls back to intent if not provided. */
  readonly intent_summary?: string;
  /**
   * AI behavior hints inferred by onboarding (or hand-authored).
   * Renders as a nested `ai_hints:` block under `project:`. v0.3.57+ (F-00eb1a).
   */
  readonly ai_hints?: {
    readonly preferred_persona?: string;
    readonly token_budget_per_session?: number;
    readonly test_framework?: string;
    readonly primary_branch?: string;
    readonly forbidden_patterns?: readonly string[];
    /** Advisory preferred-pattern triples. v0.3.58+ (F-32b1e0). */
    readonly preferred_patterns?: readonly {
      readonly when: string;
      readonly prefer: string;
      readonly over?: string;
    }[];
  };
}

function quoted(value: string): string {
  return `"${value.replace(/"/g, '\\"')}"`;
}

/** Collapses an intent string to a single short line (≤ 120 chars). */
function oneLine(text: string): string {
  const collapsed = text.replace(/\s+/g, ' ').trim();
  return collapsed.length > 120 ? `${collapsed.slice(0, 117)}…` : collapsed;
}

function hasAnyAiHint(h: NonNullable<SpecSeedMetadata['ai_hints']>): boolean {
  return Boolean(
    h.preferred_persona ||
      typeof h.token_budget_per_session === 'number' ||
      h.test_framework ||
      h.primary_branch ||
      (h.forbidden_patterns && h.forbidden_patterns.length > 0) ||
      (h.preferred_patterns && h.preferred_patterns.length > 0),
  );
}

// v0.3.49 (F-99c6e5) — `specSeed` now emits `features: []` so the
// sharded layout activates from day one. F-001 lives in
// `spec/features/F-001-<hash>.yaml` instead of inline. This unblocks
// every spec-gated detector (MISSING_IMPLEMENTATION, AC_DRIFT,
// UNTESTED_AC, …) which previously couldn't see user-authored shards
// when the inline F-001 placeholder kept the master `features` array
// non-empty.
//
// v0.3.49 (F-3a5339) — Project also accepts optional metadata (description,
// version, repository, intent_summary). When the intent path is taken,
// description + intent_summary default to the user's intent line so the
// spec.yaml front door has *something* useful instead of just name+language.
function specSeed(
  projectName: string,
  language: string,
  metadata?: SpecSeedMetadata,
  marker?: EnrichmentMarker,
): string {
  const projectLines = [
    `  name: ${projectName}`,
    `  language: ${language}`,
  ];
  if (metadata?.description) {
    projectLines.push(`  description: ${quoted(metadata.description)}`);
  }
  projectLines.push(`  version: ${quoted(metadata?.version ?? '0.0.1')}`);
  if (metadata?.repository) {
    projectLines.push(`  repository: ${quoted(metadata.repository)}`);
  }
  if (metadata?.intent_summary) {
    projectLines.push(`  intent_summary: ${quoted(metadata.intent_summary)}`);
  }
  if (metadata?.ai_hints && hasAnyAiHint(metadata.ai_hints)) {
    projectLines.push('  ai_hints:');
    const h = metadata.ai_hints;
    if (h.preferred_persona) {
      projectLines.push(`    preferred_persona: ${h.preferred_persona}`);
    }
    if (typeof h.token_budget_per_session === 'number') {
      projectLines.push(`    token_budget_per_session: ${h.token_budget_per_session}`);
    }
    if (h.test_framework) {
      projectLines.push(`    test_framework: ${h.test_framework}`);
    }
    if (h.primary_branch) {
      projectLines.push(`    primary_branch: ${h.primary_branch}`);
    }
    if (h.forbidden_patterns && h.forbidden_patterns.length > 0) {
      const list = h.forbidden_patterns.map((p) => quoted(p)).join(', ');
      projectLines.push(`    forbidden_patterns: [${list}]`);
    }
    if (h.preferred_patterns && h.preferred_patterns.length > 0) {
      projectLines.push('    preferred_patterns:');
      for (const triple of h.preferred_patterns) {
        projectLines.push(`      - when: ${quoted(triple.when)}`);
        projectLines.push(`        prefer: ${quoted(triple.prefer)}`);
        if (triple.over) {
          projectLines.push(`        over: ${quoted(triple.over)}`);
        }
      }
    }
  }

  return [
    '# Cladding · Tier A · SSoT — Iron Law sealed · Refreshed by: clad_create_feature / manual',
    `# ${projectName} — Cladding spec`,
    '# Features live in spec/features/<slug>-<hash>.yaml — one file per feature.',
    '# Edit shards there, run `clad sync` to validate, `clad check` to exercise',
    '# every Iron Law stage. See https://github.com/qwerfunch/ironclad for the standard.',
    '',
    'schema: "0.1"',
    '',
    // F-90d054 — lazy enrichment marker. Host AI consumes this on its first
    // task in the project and removes it once every scope item is filled.
    ...(marker ? [renderMarkerYaml(marker), ''] : []),
    'project:',
    ...projectLines,
    '',
    'features: []',
    '',
  ].join('\n');
}

/** Renders the placeholder F-001 shard written alongside the sharded spec.yaml seed. */
function f001SeedShard(seedTitle?: string): string {
  const title = (seedTitle ?? 'Your first feature').replace(/"/g, '\\"');
  return [
    '# Cladding · Tier A · SSoT — Iron Law sealed · Refreshed by: clad_create_feature / manual',
    'id: F-001',
    'slug: first-feature',
    `title: "${title}"`,
    'status: planned',
    'modules: []',
    'acceptance_criteria:',
    '  - id: AC-001',
    '    ears: ubiquitous',
    '    text: "Replace this with what F-001 actually shall do."',
    '',
  ].join('\n');
}

function appendIfMissing(gitignorePath: string, marker: string, line: string): boolean {
  const existing = existsSync(gitignorePath) ? readFileSync(gitignorePath, 'utf8') : '';
  if (existing.includes(marker)) return false;
  const ensureNewline = existing.length > 0 && !existing.endsWith('\n') ? '\n' : '';
  writeFileSync(gitignorePath, `${existing}${ensureNewline}\n# Cladding runtime state\n${line}\n`);
  return true;
}

/**
 * Scaffolds a cladding workspace at `cwd`. Idempotent; safe by default.
 *
 * @returns The list of created and skipped artifacts plus the detected language.
 */
export async function runInit(opts: InitOptions = {}): Promise<InitResult> {
  const cwd = opts.cwd ?? '.';
  const force = opts.force ?? false;
  const created: string[] = [];
  const skipped: string[] = [];

  // I13 (v0.3.27) — `detectToolchain` reads manifests (package.json
  // wins first), which mis-identifies polyglot repos that ship a
  // package.json for tooling but are written in Python / Go / Ruby /
  // Swift. When scan runs we also know the file-extension majority;
  // prefer that signal over the manifest guess.
  //
  // v0.3.32 — scan auto-detect. `opts.scan === false` (--no-scan)
  // skips the walker entirely; otherwise scan always runs and the
  // result decides whether conventions/architecture artifacts are
  // worth writing. `docs/project-context.md` is written regardless
  // (template when there is nothing observable).
  const detected = detectToolchain(cwd).language;
  const manifestLanguage = detected === 'unknown' ? 'typescript' : detected;
  const scanResult = opts.scan === false ? null : scanRoot({cwd, roots: opts.roots});
  const SCAN_AUTO_THRESHOLD = 3;
  const shouldWriteScanArtifacts =
    scanResult !== null &&
    (opts.scan === true || scanResult.stats.filesScanned >= SCAN_AUTO_THRESHOLD);
  const language =
    scanResult && scanResult.stats.dominantLanguage !== 'unknown' && scanResult.stats.dominantLanguage !== 'other'
      ? scanResult.stats.dominantLanguage
      : manifestLanguage;
  const projectName = opts.projectName ?? basename(resolve(cwd));
  const rawIntent = opts.intent?.trim();

  // F-5f6b45 — path-aware intent. When the positional argument looks like a
  // text-file path (.md / .txt / .yaml / .yml / .markdown) and the file exists
  // under cwd, load its contents and use them as the intent. The LLM has no
  // filesystem access; cladding must do the load before composing the prompt.
  // Anything not path-like (or a missing / non-text path) falls back to the
  // existing free-text intent behavior with a stderr warning when applicable.
  let intent = rawIntent;
  if (rawIntent && rawIntent.length > 0) {
    const resolution = loadIntentFromPathIfApplicable(rawIntent, cwd);
    if (resolution.warning) {
      process.stderr.write(`[clad init] ${resolution.warning}\n`);
    }
    if (resolution.loadedFrom) {
      process.stderr.write(`[clad init] loaded intent from ${resolution.loadedFrom}\n`);
    }
    intent = resolution.intent;
  }

  // v0.3.43 — intent-aware onboarding. When the user passes a free-text
  // intent (`clad init <description>`), run the LLM-driven onboarding
  // path that returns a domain-aware project-context body + refined
  // capabilities + architecture + a real F-001 title + product/business
  // clarifying questions. The result feeds the spec.yaml seed below and
  // the scan-artifact writes further down so the spec/docs surface is
  // intent-shaped from the first init. `--no-llm` and a missing
  // dispatcher both fall back to a deterministic variant that quotes
  // the intent verbatim.
  let onboarding: OnboardingResult | null = null;
  const dispatcher = selectDispatcher({noLlm: opts.noLlm});
  if (intent && intent.length > 0) {
    const observed: OnboardingObserved = {
      cwdBasename: basename(resolve(cwd)),
      language,
      sourceFileCount: scanResult?.stats.filesScanned ?? 0,
      readmePresent: Boolean(scanResult?.projectContext?.readmeFirstParagraph),
      readmeFirstParagraph: scanResult?.projectContext?.readmeFirstParagraph ?? null,
      projectName,
    };
    onboarding = await interpretOnboardingWithFallback(intent, observed, dispatcher, cwd);

    // v0.3.44 (F-09d68b) — persist the onboarding session so `clad refine`
    // can drive the Q&A loop without re-running the full intent prompt.
    // The state file lives at `.cladding/onboarding/state.yaml` and is
    // marked `status: done` once every question is answered.
    const initialState: OnboardingState = {
      intent,
      language,
      projectName,
      mode: onboarding.mode,
      startedAt: new Date().toISOString(),
      status: onboarding.clarifyingQuestions.length === 0 ? 'done' : 'active',
      qa: onboarding.clarifyingQuestions.map((question) => ({question, answer: null})),
    };
    saveState(cwd, initialState);
  }

  // F-90d054 — observe the project once to build the lazy enrichment marker.
  // detectContext is cheap (one synchronous walk capped at depth 12, skipping
  // node_modules/.git/dist/etc) and gives host AI the ground truth it needs
  // to populate the enrichment scope without invention.
  const ctx = detectContext(cwd);
  const marker = buildMarker(ctx);

  // 1. spec.yaml + F-001 sharded placeholder
  //
  // v0.3.49 (F-99c6e5): spec.yaml seed now carries `features: []` and
  // the F-001 placeholder lives at `spec/features/F-001-first.yaml`.
  // This activates the sharded-loader path from day one — every
  // spec-gated detector now sees user-authored shards instead of
  // being blinded by the legacy inline placeholder.
  // v0.3.60 (F-90d054): seed now carries `_meta` enrichment marker so
  // host AI can finish what `clad init` couldn't (intent reasoning,
  // ai_hints inference, EARS-shaped AC) on its first task.
  const specPath = join(cwd, 'spec.yaml');
  if (existsSync(specPath) && !force) {
    // F-90d054 AC-012 — Idempotent re-run. Preserve every line of the existing
    // spec body and only refresh `_meta` when `detected` observations actually
    // changed. The host AI then sees the new pending scope on its next task.
    const existing = readFileSync(specPath, 'utf8');
    const patched = patchMarkerInSpec(existing, ctx);
    if (patched.updated) {
      writeFileSync(specPath, patched.body);
      created.push(
        `spec.yaml (_meta refreshed; re-activated: ${patched.reactivated.join(', ')})`,
      );
    } else {
      skipped.push('spec.yaml (exists; _meta already current)');
    }
  } else {
    // v0.3.49 (F-3a5339) — when an intent is provided, seed the
    // project metadata fields too so spec.yaml has a meaningful
    // "front door". v0.3.57 (F-00eb1a) — onboarding.aiHints (if
    // the LLM returned PROJECT_METADATA) flows through to spec.yaml
    // so AI agents read inferred hints at session start.
    const seedMetadata: SpecSeedMetadata | undefined = intent
      ? {
          description: oneLine(intent),
          intent_summary: oneLine(intent),
          ai_hints: onboarding?.aiHints,
        }
      : undefined;
    writeFileSync(specPath, specSeed(projectName, language, seedMetadata, marker));
    created.push('spec.yaml');
  }
  const f001Path = join(cwd, 'spec', 'features', 'F-001-first.yaml');
  if (existsSync(f001Path) && !force) {
    skipped.push('spec/features/F-001-first.yaml (exists; pass --force to overwrite)');
  } else {
    mkdirSync(dirname(f001Path), {recursive: true});
    writeFileSync(f001Path, f001SeedShard(onboarding?.specSeedTitle));
    created.push('spec/features/F-001-first.yaml');
  }

  // 2. .cladding/ runtime dir
  const claddingDir = join(cwd, '.cladding');
  if (existsSync(claddingDir)) {
    skipped.push('.cladding/ (exists)');
  } else {
    mkdirSync(claddingDir, {recursive: true});
    created.push('.cladding/');
  }

  // 3. .gitignore append
  const gitignorePath = join(cwd, '.gitignore');
  const appended = appendIfMissing(gitignorePath, '.cladding/', '.cladding/');
  if (appended) {
    created.push('.gitignore (.cladding/ entry appended)');
  } else {
    skipped.push('.gitignore (.cladding/ entry already present)');
  }

  const proposals: string[] = [];

  // v0.3.35 — dispatcher is selected once at the top of runInit (see
  // intent-onboarding section above) and threaded through every
  // refinement path so a hosted environment touches the LLM at most
  // once per cycle. --no-llm / no-key / no-host all collapse to
  // deterministic for byte-stable CI output.

  // Phase 2 (v0.3.24, F-x) — Existing-project scan. When the scan
  // gate fires we walk `cwd` for code conventions, layers, and
  // representative modules, then write three artifacts (or divert
  // them to `.cladding/scan/*.proposal.*` if the authored copies
  // already exist).
  //
  // v0.3.35 — interpretScanWithFallback awaits the LLM when a
  // dispatcher is available (polished prose for docs/conventions.md
  // and richer responsibility comments for spec/architecture.yaml)
  // and collapses to deterministicInterpret on null/error so the
  // artifacts are always usable.
  if (shouldWriteScanArtifacts && scanResult) {
    const interp: InterpretedScan = await interpretScanWithFallback(scanResult, dispatcher, cwd);

    writeArtifact(cwd, 'docs/conventions.md', interp.conventionsMd, created, proposals);
    writeArtifact(cwd, 'spec/architecture.yaml', interp.architectureYaml, created, proposals);

    // v0.3.38 — README ## headings are mirrored into a first-class spec
    // artifact so downstream detectors can read the capability list
    // directly instead of re-parsing docs/project-context.md. LLM
    // refinement (when a dispatcher is available) adds `summary` +
    // `surface` per entry; deterministic mode ships id + title only.
    writeArtifact(cwd, 'spec/capabilities.yaml', interp.capabilitiesYaml, created, proposals);

    // v0.3.30 — scenarios are not auto-extracted from observed code.
    // A user journey is *intent*, not architecture, so cladding leaves
    // the directory empty at adoption time and registers scenarios
    // when the user requests features through `clad_create_feature`.
    // The README documents the policy so reviewers don't expect
    // populated YAMLs.
    writeArtifact(cwd, 'spec/scenarios/README.md', SCENARIOS_README, created, proposals);
  } else {
    // v0.3.42 — greenfield seeds. When no code has been observed yet
    // (auto-scan threshold of 3 source files not met, or `--no-scan`),
    // ship the three scan-derived artifacts as toolchain-default
    // templates so the spec/docs surface is always complete. Personas
    // can then drop the "if absent" branch from their guidance; a
    // later `clad init --scan` on a populated codebase will replace
    // these bodies via the existing `.cladding/scan/*.proposal`
    // divert mechanism in `writeArtifact`.
    //
    // v0.3.43 — when intent is provided, the onboarding pass produces
    // domain-aware capabilities + architecture bodies that replace the
    // toolchain-default seeds. `conventions.md` stays seed-based
    // because conventions are language-specific, not domain-specific.
    writeArtifact(cwd, 'docs/conventions.md', renderGreenfieldConventionsMd(language, projectName), created, proposals);
    writeArtifact(
      cwd,
      'spec/architecture.yaml',
      onboarding?.architectureYaml ?? renderGreenfieldArchitectureYaml(language),
      created,
      proposals,
    );
    writeArtifact(
      cwd,
      'spec/capabilities.yaml',
      onboarding?.capabilitiesYaml ?? renderGreenfieldCapabilitiesYaml(projectName),
      created,
      proposals,
    );
    writeArtifact(cwd, 'spec/scenarios/README.md', SCENARIOS_README, created, proposals);
  }

  // v0.3.32 — `docs/project-context.md` is the forest-level entry
  // document and ships in *every* cladding workspace regardless of
  // whether the scan artifacts were written.
  //
  // v0.3.33 — when an LLM dispatcher is available the Why / What /
  // Purpose sections are refined from observed README/docs into
  // polished prose. Greenfield + no-LLM environments still receive
  // the deterministic template; the dispatcher failure path also
  // collapses to deterministic so the file is always usable.
  //
  // v0.3.43 — when intent is provided, the onboarding pass produces a
  // richer body that captures the user's stated intent plus inferred
  // domain context. That body wins over the observed-README path.
  const projectContext = scanResult?.projectContext ?? null;
  let projectContextMd: string;
  if (onboarding) {
    projectContextMd = onboarding.projectContextMd;
  } else if (dispatcher) {
    projectContextMd = await renderProjectContextMdWithLlm(projectContext, projectName, dispatcher, cwd);
  } else {
    projectContextMd = renderProjectContextMd(projectContext, projectName);
  }
  writeArtifact(cwd, 'docs/project-context.md', projectContextMd, created, proposals);

  // v0.3.45 (F-d12edf) — onboarding scenarios. Each scenario from the
  // intent-aware onboarding lands in spec/scenarios/<slug>-<hash6>.yaml
  // so `clad_create_feature` can later bind new features to them via
  // the features[] array. Scenarios are Tier A (sealed by detectors)
  // but onboarding-time editable — see docs/ssot-model.md.
  if (onboarding && onboarding.scenarios.length > 0) {
    for (const scenario of onboarding.scenarios) {
      const hash = scenario.id.replace(/^S-/, '');
      const filename = `spec/scenarios/${scenario.slug}-${hash}.yaml`;
      const body = renderScenarioYaml(scenario);
      writeArtifact(cwd, filename, body, created, proposals);
    }
  }

  // F-90d054 — project-local host AI instruction surfaces.
  // AGENTS.md is the cross-tool entry point (Codex · Cursor · Continue ·
  // Copilot · Aider). CLAUDE.md is Claude Code's project memory — appended
  // idempotently so existing user content is preserved.
  const agentsResult = writeAgentsMd(cwd, {force});
  if (agentsResult === 'created' || agentsResult === 'overwritten') {
    created.push('AGENTS.md');
  } else {
    skipped.push('AGENTS.md (exists; pass --force to overwrite)');
  }
  const claudeResult = writeClaudeMdSection(cwd, {force});
  if (claudeResult === 'created') {
    created.push('CLAUDE.md');
  } else if (claudeResult === 'appended') {
    created.push('CLAUDE.md (## cladding section appended)');
  } else {
    skipped.push('CLAUDE.md (## cladding section already present)');
  }

  // F-80d19d — friendly warning when host channels were never wired or are
  // out of sync with the current cladding binary. `clad setup` is the explicit
  // command for wiring; this is informational only and does not block init.
  const lastSetup = getLastSetupVersion();
  const pkgVersion = getCurrentCladdingVersion();
  if (lastSetup == null) {
    skipped.push(
      'host channels not wired yet — run `clad setup` to enable `/cladding init` from Claude Code / Codex / Gemini',
    );
  } else if (pkgVersion && lastSetup !== pkgVersion) {
    skipped.push(
      `host wire was set up at v${lastSetup} (current binary v${pkgVersion}) — symlinks usually auto-follow, but run \`clad setup\` to be sure`,
    );
  }

  return {
    created,
    skipped,
    language,
    proposals: proposals.length ? proposals : undefined,
    clarifyingQuestions: onboarding?.clarifyingQuestions.length ? [...onboarding.clarifyingQuestions] : undefined,
    onboardingMode: onboarding?.mode,
  };
}

/**
 * Renders one onboarding scenario as a YAML shard ready for
 * `spec/scenarios/<slug>-<hash>.yaml`. Schema mirrors the existing
 * sharded scenario format (`id`, `slug`, `title`, `flow`, `features`).
 * The header banner identifies the artifact as Tier A SSoT per
 * `docs/ssot-model.md`.
 */
function renderScenarioYaml(scenario: {
  readonly id: string;
  readonly slug: string;
  readonly title: string;
  readonly flow: string;
  readonly features: readonly string[];
}): string {
  const escapedTitle = scenario.title.replace(/"/g, '\\"');
  const flowLines = scenario.flow.split('\n').map((line) => `  ${line}`).join('\n');
  return [
    '# Cladding · Tier A · SSoT — onboarding output, edit-friendly · Refreshed by: clad init / clad refine',
    `id: ${scenario.id}`,
    `slug: ${scenario.slug}`,
    `title: "${escapedTitle}"`,
    'flow: |',
    flowLines || '  (no flow described)',
    'features: []',
    '',
  ].join('\n');
}

/**
 * Writes `relPath` under `cwd`. When the target already exists the
 * payload is diverted to `.cladding/scan/<basename>.proposal.<ext>`
 * instead of overwriting authored content. Either way the resulting
 * path lands in `created` or `proposals` so the CLI handler can
 * report it.
 */
function writeArtifact(
  cwd: string,
  relPath: string,
  body: string,
  created: string[],
  proposals: string[],
): void {
  const target = join(cwd, relPath);
  if (existsSync(target)) {
    const proposal = join(cwd, '.cladding', 'scan', `${basename(relPath)}.proposal`);
    mkdirSync(dirname(proposal), {recursive: true});
    writeFileSync(proposal, body);
    proposals.push(`${relPath} → ${relPath.startsWith('docs/') || relPath.startsWith('spec/') ? '.cladding/scan/' : ''}${basename(relPath)}.proposal`);
    return;
  }
  mkdirSync(dirname(target), {recursive: true});
  writeFileSync(target, body);
  created.push(relPath);
}
