// Cladding · `clad init` — workspace scaffolder
//
// One command, three side-effects on a fresh directory:
//   1. spec.yaml seed with one placeholder feature (F-001)
//   2. .cladding/ runtime dir (audit + events log live here)
//   3. .gitignore append (.cladding/ entry; appended only if missing)
//
// Idempotent by default — re-running on an initialised workspace is a
// no-op except for reporting. `--force` overwrites the seed spec.yaml
// (other artifacts stay safe). Language is auto-detected from the
// manifest chain (package.json / pyproject.toml / Cargo.toml / …);
// `unknown` falls back to typescript so the seed is always valid.

import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {basename, dirname, join, resolve} from 'node:path';

import {
  interpretScanWithFallback,
  renderProjectContextMd,
  renderProjectContextMdWithLlm,
  scanRoot,
  selectDispatcher,
  type InterpretedScan,
} from './scan/index.js';
import {
  renderGreenfieldArchitectureYaml,
  renderGreenfieldCapabilitiesYaml,
  renderGreenfieldConventionsMd,
} from './scan/greenfield-seeds.js';
import {
  interpretOnboardingWithFallback,
  type OnboardingObserved,
  type OnboardingResult,
} from './scan/intent-onboarding.js';
import {saveState, type OnboardingState} from './scan/onboarding-state.js';
import {detectToolchain} from '../stages/toolchain/detect.js';

export interface InitOptions {
  readonly cwd?: string;
  readonly projectName?: string;
  readonly force?: boolean;
  /** Walks the existing codebase and writes docs/conventions.md + spec/architecture.yaml + scenario stubs. */
  readonly scan?: boolean;
  /** Forces the deterministic-only fallback even when an LLM dispatcher is available. */
  readonly noLlm?: boolean;
  /** Source-root override for the scanner, e.g. ["packages/a/src", "packages/b/src"]. */
  readonly roots?: readonly string[];
  /**
   * Free-text user intent (v0.3.43+). When provided, init routes through
   * the LLM-driven onboarding path (`intent-onboarding.ts`) which produces
   * domain-aware seeds for project-context / capabilities / architecture
   * plus a real F-001 title and 2-3 follow-up questions. When omitted,
   * init falls back to the v0.3.42 behaviour (toolchain-default seeds in
   * greenfield, observed scan otherwise).
   */
  readonly intent?: string;
}

export interface InitResult {
  readonly created: readonly string[];
  readonly skipped: readonly string[];
  readonly language: string;
  /** Files diverted to `.cladding/scan/*.proposal.*` because an authored copy already existed. */
  readonly proposals?: readonly string[];
  /**
   * Product/business-level follow-up questions emitted by the LLM during
   * intent-aware onboarding. Empty when no intent was given or when the
   * deterministic fallback fired. The CLI surfaces these as hints.
   */
  readonly clarifyingQuestions?: readonly string[];
  /** Mode the onboarding pass classified the project as (intent path only). */
  readonly onboardingMode?: OnboardingResult['mode'];
}

// v0.3.30 — Scenarios in cladding capture *user journeys* (business
// intent), not architecture layers. Cladding writes this README at
// adoption time so reviewers understand why the directory is empty
// and how it grows.
const SCENARIOS_README = [
  '<!-- Auto-generated by `clad init --scan`. Do not author scenario YAML by hand. -->',
  '',
  '# Scenarios',
  '',
  'Scenarios in cladding capture **user journeys** — the business flows your',
  'system enables, not the architecture layers your code is organised into.',
  '',
  'You do not author scenario YAML by hand. They are auto-registered when you',
  'request a feature through `clad_create_feature` or through natural-language',
  'conversation with your AI host. The scenario your request belongs to is',
  'inferred together with the feature itself.',
  '',
  'This directory is intentionally empty at scan time. The first scenario lands',
  'when you ship the first feature.',
  '',
  '## Why not auto-extract from existing code?',
  '',
  'A user journey is *intent* — the question your codebase answers for the',
  'people who use it. Cladding could guess at intent from routers, README',
  'headings, or call graphs, but those are *architecture signals*, not journey',
  'signals. Guesses ship as authoritative YAML and mislead reviewers. Cladding',
  'instead waits for you to declare intent through a feature request and binds',
  'the scenario to that declaration.',
  '',
  '## See also',
  '',
  '- `docs/conventions.md` — observed conventions (auto-generated)',
  '- `spec/architecture.yaml` — observed layers + forbidden_imports candidates',
  '- `spec.yaml` — feature registry (grown by clad_create_feature)',
  '',
].join('\n');

function specSeed(projectName: string, language: string, seedTitle?: string): string {
  const title = (seedTitle ?? 'Your first feature').replace(/"/g, '\\"');
  return [
    `# ${projectName} — Cladding spec`,
    '# This file is your project SSoT. Edit features here, run `clad sync`',
    '# to validate, and `clad check` to exercise every Iron Law stage.',
    '# See https://github.com/qwerfunch/ironclad for the standard.',
    '',
    'schema: "0.1"',
    '',
    'project:',
    `  name: ${projectName}`,
    `  language: ${language}`,
    '',
    'features:',
    '  - id: F-001',
    `    title: "${title}"`,
    '    status: planned',
    '    modules: []',
    '    acceptance_criteria:',
    '      - id: AC-001',
    '        ears: ubiquitous',
    '        text: "Replace this with what F-001 actually shall do."',
    '',
  ].join('\n');
}

function appendIfMissing(gitignorePath: string, marker: string, line: string): boolean {
  const existing = existsSync(gitignorePath) ? readFileSync(gitignorePath, 'utf8') : '';
  if (existing.includes(marker)) return false;
  const ensureNewline = existing.length > 0 && !existing.endsWith('\n') ? '\n' : '';
  writeFileSync(gitignorePath, `${existing}${ensureNewline}\n# Cladding runtime state\n${line}\n`);
  return true;
}

/**
 * Scaffolds a cladding workspace at `cwd`. Idempotent; safe by default.
 *
 * @returns The list of created and skipped artifacts plus the detected language.
 */
export async function runInit(opts: InitOptions = {}): Promise<InitResult> {
  const cwd = opts.cwd ?? '.';
  const force = opts.force ?? false;
  const created: string[] = [];
  const skipped: string[] = [];

  // I13 (v0.3.27) — `detectToolchain` reads manifests (package.json
  // wins first), which mis-identifies polyglot repos that ship a
  // package.json for tooling but are written in Python / Go / Ruby /
  // Swift. When scan runs we also know the file-extension majority;
  // prefer that signal over the manifest guess.
  //
  // v0.3.32 — scan auto-detect. `opts.scan === false` (--no-scan)
  // skips the walker entirely; otherwise scan always runs and the
  // result decides whether conventions/architecture artifacts are
  // worth writing. `docs/project-context.md` is written regardless
  // (template when there is nothing observable).
  const detected = detectToolchain(cwd).language;
  const manifestLanguage = detected === 'unknown' ? 'typescript' : detected;
  const scanResult = opts.scan === false ? null : scanRoot({cwd, roots: opts.roots});
  const SCAN_AUTO_THRESHOLD = 3;
  const shouldWriteScanArtifacts =
    scanResult !== null &&
    (opts.scan === true || scanResult.stats.filesScanned >= SCAN_AUTO_THRESHOLD);
  const language =
    scanResult && scanResult.stats.dominantLanguage !== 'unknown' && scanResult.stats.dominantLanguage !== 'other'
      ? scanResult.stats.dominantLanguage
      : manifestLanguage;
  const projectName = opts.projectName ?? basename(resolve(cwd));
  const intent = opts.intent?.trim();

  // v0.3.43 — intent-aware onboarding. When the user passes a free-text
  // intent (`clad init <description>`), run the LLM-driven onboarding
  // path that returns a domain-aware project-context body + refined
  // capabilities + architecture + a real F-001 title + product/business
  // clarifying questions. The result feeds the spec.yaml seed below and
  // the scan-artifact writes further down so the spec/docs surface is
  // intent-shaped from the first init. `--no-llm` and a missing
  // dispatcher both fall back to a deterministic variant that quotes
  // the intent verbatim.
  let onboarding: OnboardingResult | null = null;
  const dispatcher = selectDispatcher({noLlm: opts.noLlm});
  if (intent && intent.length > 0) {
    const observed: OnboardingObserved = {
      cwdBasename: basename(resolve(cwd)),
      language,
      sourceFileCount: scanResult?.stats.filesScanned ?? 0,
      readmePresent: Boolean(scanResult?.projectContext?.readmeFirstParagraph),
      readmeFirstParagraph: scanResult?.projectContext?.readmeFirstParagraph ?? null,
      projectName,
    };
    onboarding = await interpretOnboardingWithFallback(intent, observed, dispatcher, cwd);

    // v0.3.44 (F-09d68b) — persist the onboarding session so `clad refine`
    // can drive the Q&A loop without re-running the full intent prompt.
    // The state file lives at `.cladding/onboarding/state.yaml` and is
    // marked `status: done` once every question is answered.
    const initialState: OnboardingState = {
      intent,
      language,
      projectName,
      mode: onboarding.mode,
      startedAt: new Date().toISOString(),
      status: onboarding.clarifyingQuestions.length === 0 ? 'done' : 'active',
      qa: onboarding.clarifyingQuestions.map((question) => ({question, answer: null})),
    };
    saveState(cwd, initialState);
  }

  // 1. spec.yaml
  const specPath = join(cwd, 'spec.yaml');
  if (existsSync(specPath) && !force) {
    skipped.push('spec.yaml (exists; pass --force to overwrite)');
  } else {
    writeFileSync(specPath, specSeed(projectName, language, onboarding?.specSeedTitle));
    created.push('spec.yaml');
  }

  // 2. .cladding/ runtime dir
  const claddingDir = join(cwd, '.cladding');
  if (existsSync(claddingDir)) {
    skipped.push('.cladding/ (exists)');
  } else {
    mkdirSync(claddingDir, {recursive: true});
    created.push('.cladding/');
  }

  // 3. .gitignore append
  const gitignorePath = join(cwd, '.gitignore');
  const appended = appendIfMissing(gitignorePath, '.cladding/', '.cladding/');
  if (appended) {
    created.push('.gitignore (.cladding/ entry appended)');
  } else {
    skipped.push('.gitignore (.cladding/ entry already present)');
  }

  const proposals: string[] = [];

  // v0.3.35 — dispatcher is selected once at the top of runInit (see
  // intent-onboarding section above) and threaded through every
  // refinement path so a hosted environment touches the LLM at most
  // once per cycle. --no-llm / no-key / no-host all collapse to
  // deterministic for byte-stable CI output.

  // Phase 2 (v0.3.24, F-x) — Existing-project scan. When the scan
  // gate fires we walk `cwd` for code conventions, layers, and
  // representative modules, then write three artifacts (or divert
  // them to `.cladding/scan/*.proposal.*` if the authored copies
  // already exist).
  //
  // v0.3.35 — interpretScanWithFallback awaits the LLM when a
  // dispatcher is available (polished prose for docs/conventions.md
  // and richer responsibility comments for spec/architecture.yaml)
  // and collapses to deterministicInterpret on null/error so the
  // artifacts are always usable.
  if (shouldWriteScanArtifacts && scanResult) {
    const interp: InterpretedScan = await interpretScanWithFallback(scanResult, dispatcher, cwd);

    writeArtifact(cwd, 'docs/conventions.md', interp.conventionsMd, created, proposals);
    writeArtifact(cwd, 'spec/architecture.yaml', interp.architectureYaml, created, proposals);

    // v0.3.38 — README ## headings are mirrored into a first-class spec
    // artifact so downstream detectors can read the capability list
    // directly instead of re-parsing docs/project-context.md. LLM
    // refinement (when a dispatcher is available) adds `summary` +
    // `surface` per entry; deterministic mode ships id + title only.
    writeArtifact(cwd, 'spec/capabilities.yaml', interp.capabilitiesYaml, created, proposals);

    // v0.3.30 — scenarios are not auto-extracted from observed code.
    // A user journey is *intent*, not architecture, so cladding leaves
    // the directory empty at adoption time and registers scenarios
    // when the user requests features through `clad_create_feature`.
    // The README documents the policy so reviewers don't expect
    // populated YAMLs.
    writeArtifact(cwd, 'spec/scenarios/README.md', SCENARIOS_README, created, proposals);
  } else {
    // v0.3.42 — greenfield seeds. When no code has been observed yet
    // (auto-scan threshold of 3 source files not met, or `--no-scan`),
    // ship the three scan-derived artifacts as toolchain-default
    // templates so the spec/docs surface is always complete. Personas
    // can then drop the "if absent" branch from their guidance; a
    // later `clad init --scan` on a populated codebase will replace
    // these bodies via the existing `.cladding/scan/*.proposal`
    // divert mechanism in `writeArtifact`.
    //
    // v0.3.43 — when intent is provided, the onboarding pass produces
    // domain-aware capabilities + architecture bodies that replace the
    // toolchain-default seeds. `conventions.md` stays seed-based
    // because conventions are language-specific, not domain-specific.
    writeArtifact(cwd, 'docs/conventions.md', renderGreenfieldConventionsMd(language, projectName), created, proposals);
    writeArtifact(
      cwd,
      'spec/architecture.yaml',
      onboarding?.architectureYaml ?? renderGreenfieldArchitectureYaml(language),
      created,
      proposals,
    );
    writeArtifact(
      cwd,
      'spec/capabilities.yaml',
      onboarding?.capabilitiesYaml ?? renderGreenfieldCapabilitiesYaml(projectName),
      created,
      proposals,
    );
    writeArtifact(cwd, 'spec/scenarios/README.md', SCENARIOS_README, created, proposals);
  }

  // v0.3.32 — `docs/project-context.md` is the forest-level entry
  // document and ships in *every* cladding workspace regardless of
  // whether the scan artifacts were written.
  //
  // v0.3.33 — when an LLM dispatcher is available the Why / What /
  // Purpose sections are refined from observed README/docs into
  // polished prose. Greenfield + no-LLM environments still receive
  // the deterministic template; the dispatcher failure path also
  // collapses to deterministic so the file is always usable.
  //
  // v0.3.43 — when intent is provided, the onboarding pass produces a
  // richer body that captures the user's stated intent plus inferred
  // domain context. That body wins over the observed-README path.
  const projectContext = scanResult?.projectContext ?? null;
  let projectContextMd: string;
  if (onboarding) {
    projectContextMd = onboarding.projectContextMd;
  } else if (dispatcher) {
    projectContextMd = await renderProjectContextMdWithLlm(projectContext, projectName, dispatcher, cwd);
  } else {
    projectContextMd = renderProjectContextMd(projectContext, projectName);
  }
  writeArtifact(cwd, 'docs/project-context.md', projectContextMd, created, proposals);

  return {
    created,
    skipped,
    language,
    proposals: proposals.length ? proposals : undefined,
    clarifyingQuestions: onboarding?.clarifyingQuestions.length ? [...onboarding.clarifyingQuestions] : undefined,
    onboardingMode: onboarding?.mode,
  };
}

/**
 * Writes `relPath` under `cwd`. When the target already exists the
 * payload is diverted to `.cladding/scan/<basename>.proposal.<ext>`
 * instead of overwriting authored content. Either way the resulting
 * path lands in `created` or `proposals` so the CLI handler can
 * report it.
 */
function writeArtifact(
  cwd: string,
  relPath: string,
  body: string,
  created: string[],
  proposals: string[],
): void {
  const target = join(cwd, relPath);
  if (existsSync(target)) {
    const proposal = join(cwd, '.cladding', 'scan', `${basename(relPath)}.proposal`);
    mkdirSync(dirname(proposal), {recursive: true});
    writeFileSync(proposal, body);
    proposals.push(`${relPath} → ${relPath.startsWith('docs/') || relPath.startsWith('spec/') ? '.cladding/scan/' : ''}${basename(relPath)}.proposal`);
    return;
  }
  mkdirSync(dirname(target), {recursive: true});
  writeFileSync(target, body);
  created.push(relPath);
}
