// Cladding · plugin asset builder (v0.3.1 → v0.3.6, F-076 · F-077 · F-081).
//
// Single source of truth: src/agents/*.md (personas) + skills/*/SKILL.md
// (verbs). This script generates the host-specific plugin layouts:
//
//   Claude Code (repo root, v0.3.1, F-076):
//     agents/<id>.md       ← src/agents/<id>.md (verbatim copy)
//     skills/<verb>/...    ← already authored at repo root (canonical)
//     .mcp.json            ← already at repo root (canonical)
//
//   Codex (plugins/codex/, v0.3.2, F-077):
//     skills/<verb>/SKILL.md   ← copied from repo-root skills/<verb>/SKILL.md
//     skills/<persona>/SKILL.md ← src/agents/<persona>.md re-wrapped as SKILL.md
//     .mcp.json             ← already authored under plugins/codex/
//     .codex-plugin/plugin.json ← already authored
//
//   Gemini CLI (plugins/gemini-cli/, v0.3.6, F-081):
//     commands/<verb>.toml ← transpiled from repo-root skills/<verb>/SKILL.md
//                            (frontmatter.description → toml `description`,
//                             body → toml `prompt` as a literal multi-line)
//     gemini-extension.json + GEMINI.md already authored.
//
// The src side stays canonical — every loadPersona() call in the
// runtime reads from src/agents. The drift detector enforces lockstep.
//
// Run: `npm run build:plugin` or as part of `npm run build`.

import {copyFileSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';

import {parse as parseYaml} from 'yaml';

const SRC_AGENTS = 'src/agents';
const SRC_SKILLS = 'skills';
const SRC_DETECTORS = 'src/stages/detectors';
const CLAUDE_PLUGIN_JSON = '.claude-plugin/plugin.json';

// --- Phase A — Claude Code mirror (repo-root agents/) -----------------

const CLAUDE_AGENTS = 'agents';
mkdirSync(CLAUDE_AGENTS, {recursive: true});

const claudeGenerated = [];
for (const entry of readdirSync(SRC_AGENTS)) {
  if (!entry.endsWith('.md')) continue;
  if (entry === 'README.md') continue;
  const src = join(SRC_AGENTS, entry);
  if (!statSync(src).isFile()) continue;
  copyFileSync(src, join(CLAUDE_AGENTS, entry));
  claudeGenerated.push(entry);
}
writeFileSync(
  join(CLAUDE_AGENTS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs — do not edit. -->\n' +
    '<!-- Edit src/agents/<id>.md (the canonical source) instead. -->\n' +
    '\n' +
    '# Cladding plugin · agents/\n' +
    '\n' +
    'This directory is the Claude Code plugin manifest mirror of `src/agents/`.\n' +
    'Files here are copied verbatim from `src/agents/` by\n' +
    '`scripts/build-plugin.mjs` (run by `npm run build:plugin`).\n' +
    '\n' +
    'Edit the source under `src/agents/<id>.md`, then re-run the build.\n',
);
console.log(`cladding plugin · claude-code: copied ${claudeGenerated.length} agents → ${CLAUDE_AGENTS}/`);

// --- Phase B — Codex mirror (plugins/codex/skills/) -------------------

const CODEX_SKILLS = 'plugins/codex/skills';
mkdirSync(CODEX_SKILLS, {recursive: true});

// 1) verb skills — copied verbatim from repo-root `skills/<verb>/SKILL.md`
let codexVerbCount = 0;
for (const verb of readdirSync(SRC_SKILLS)) {
  const srcDir = join(SRC_SKILLS, verb);
  if (!statSync(srcDir).isDirectory()) continue;
  const srcFile = join(srcDir, 'SKILL.md');
  try {
    statSync(srcFile);
  } catch {
    continue;
  }
  const dstDir = join(CODEX_SKILLS, verb);
  mkdirSync(dstDir, {recursive: true});
  copyFileSync(srcFile, join(dstDir, 'SKILL.md'));
  codexVerbCount++;
}

// 2) persona skills — re-wrap src/agents/<id>.md as Codex SKILL.md
// The persona files already use YAML frontmatter with name + description
// + tools + capabilities; Codex's SKILL.md spec accepts arbitrary
// frontmatter and only requires `description`. The verbatim copy
// satisfies that — no transformation needed for v0.3.2.
let codexPersonaCount = 0;
for (const entry of readdirSync(SRC_AGENTS)) {
  if (!entry.endsWith('.md')) continue;
  if (entry === 'README.md') continue;
  const src = join(SRC_AGENTS, entry);
  if (!statSync(src).isFile()) continue;
  const personaId = entry.replace(/\.md$/, '');
  const dstDir = join(CODEX_SKILLS, personaId);
  mkdirSync(dstDir, {recursive: true});
  // Read + re-emit so we can confirm the YAML frontmatter has a
  // `description` field (Codex requires it). For v0.3.2 we trust the
  // src/agents files; if a future agent lacks description, the build
  // logs a warning and copies anyway.
  const content = readFileSync(src, 'utf8');
  if (!/^---\n[\s\S]*?\ndescription:/m.test(content)) {
    console.warn(`cladding plugin · codex: ${entry} lacks 'description' frontmatter — Codex may reject the skill.`);
  }
  writeFileSync(join(dstDir, 'SKILL.md'), content);
  codexPersonaCount++;
}

writeFileSync(
  join(CODEX_SKILLS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs — do not edit. -->\n' +
    '<!-- Edit src/agents/<id>.md or skills/<verb>/SKILL.md instead. -->\n' +
    '\n' +
    '# Cladding Codex plugin · skills/\n' +
    '\n' +
    'This directory is the Codex plugin manifest mirror, generated from\n' +
    'two canonical sources by `scripts/build-plugin.mjs`:\n' +
    '\n' +
    '- `<verb>/SKILL.md` ← copied verbatim from repo-root `skills/<verb>/SKILL.md`\n' +
    '- `<persona>/SKILL.md` ← copied verbatim from `src/agents/<persona>.md`\n' +
    '\n' +
    'Re-run `npm run build:plugin` after editing either source.\n',
);
console.log(
  `cladding plugin · codex: copied ${codexVerbCount} verbs + ${codexPersonaCount} personas → ${CODEX_SKILLS}/`,
);

// --- Phase C — Gemini CLI mirror (plugins/gemini-cli/commands/) -------

const GEMINI_COMMANDS = 'plugins/gemini-cli/commands';
mkdirSync(GEMINI_COMMANDS, {recursive: true});

/**
 * Splits a SKILL.md into its YAML frontmatter object and the body.
 * Returns null when no frontmatter delimiter is present so the
 * caller can decide whether to warn or skip.
 */
function splitFrontmatter(raw) {
  if (!raw.startsWith('---\n')) return null;
  const end = raw.indexOf('\n---\n', 4);
  if (end === -1) return null;
  const yamlText = raw.slice(4, end);
  const body = raw.slice(end + 5);
  return {frontmatter: parseYaml(yamlText) ?? {}, body};
}

/**
 * Escapes a string for TOML basic-string syntax (`"..."`).
 * - `\` → `\\`
 * - `"` → `\"`
 * Apostrophes pass through. Control chars are NOT scrubbed; cladding
 * skill descriptions are author-controlled prose and never contain
 * them in practice.
 */
function escapeTomlBasic(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/**
 * Renders a SKILL.md description + body into a TOML file Gemini CLI
 * accepts. Strategy:
 * - `description = "<escaped-basic-string>"` — single-line value.
 * - `prompt = '''<literal-multi-line>'''` — literal multi-line so
 *   backticks, backslashes, and other markdown punctuation pass
 *   through unaltered. The only escape concern is `'''` inside the
 *   body itself; we detect that case and fall back to the basic
 *   multi-line form (`"""..."""`) with appropriate escapes.
 */
function renderToml(description, body) {
  const desc = `description = "${escapeTomlBasic(description)}"`;
  if (!body.includes("'''")) {
    // Trim trailing whitespace but keep a leading newline for
    // readability — the closing `'''` lands on its own line.
    const trimmed = body.replace(/\s+$/, '');
    return `${desc}\nprompt = '''\n${trimmed}\n'''\n`;
  }
  // Fallback: body contains the literal sequence ' x 3, so use the
  // basic multi-line form and escape backslashes + double quotes.
  const escaped = body.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\s+$/, '');
  return `${desc}\nprompt = """\n${escaped}\n"""\n`;
}

let geminiVerbCount = 0;
const geminiWarnings = [];
for (const verb of readdirSync(SRC_SKILLS)) {
  const srcDir = join(SRC_SKILLS, verb);
  if (!statSync(srcDir).isDirectory()) continue;
  const srcFile = join(srcDir, 'SKILL.md');
  try {
    statSync(srcFile);
  } catch {
    continue;
  }
  const raw = readFileSync(srcFile, 'utf8');
  const split = splitFrontmatter(raw);
  if (!split) {
    geminiWarnings.push(`${srcFile}: no YAML frontmatter — skipped`);
    continue;
  }
  const description = String(split.frontmatter.description ?? '').trim();
  if (!description) {
    geminiWarnings.push(`${srcFile}: frontmatter has no description field — skipped`);
    continue;
  }
  const body = split.body.trimStart();
  const toml = renderToml(description, body);
  writeFileSync(join(GEMINI_COMMANDS, `${verb}.toml`), toml);
  geminiVerbCount++;
}

// AUTO-GENERATED sentinel — same pattern the Claude Code mirror uses.
writeFileSync(
  join(GEMINI_COMMANDS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs — do not edit. -->\n' +
    '<!-- Edit skills/<verb>/SKILL.md (the canonical source) instead. -->\n' +
    '\n' +
    '# Cladding Gemini CLI plugin · commands/\n' +
    '\n' +
    'This directory is the Gemini CLI plugin manifest mirror, generated\n' +
    'by `scripts/build-plugin.mjs` from `skills/<verb>/SKILL.md`:\n' +
    '\n' +
    '- `description` ← SKILL.md frontmatter `description`\n' +
    '- `prompt` ← SKILL.md body (after frontmatter)\n' +
    '\n' +
    'TOML output uses literal multi-line strings (`\'\'\'…\'\'\'`) so\n' +
    'backticks and backslashes pass through unaltered.\n' +
    '\n' +
    'Re-run `npm run build:plugin` after editing the source.\n',
);

for (const w of geminiWarnings) {
  console.warn(`cladding plugin · gemini-cli: WARN ${w}`);
}
console.log(`cladding plugin · gemini-cli: transpiled ${geminiVerbCount} verbs → ${GEMINI_COMMANDS}/`);

// --- Phase D — Detector count auto-recompute (v0.3.17, F-092) ---------
//
// HARNESS_INTEGRITY detects drift between the count of non-index files
// under src/stages/detectors/ and the `N/M` value declared in
// .claude-plugin/plugin.json `ironclad.current.detectors` (and `.target`).
// Two concurrent branches each adding +1 detector merge cleanly on the
// file side but silently leave `(N+1)/(N+1)` instead of `(N+2)/(N+2)`
// because manual edits don't compose.
//
// This phase recomputes the count from the filesystem (the single
// source of truth) and rewrites both `current.detectors` and
// `target.detectors`. The build is idempotent — re-running with no
// changes produces no diff.
//
// Rewriting preserves byte layout: rather than parsing + reserializing
// the JSON (which would normalize formatting and produce nuisance
// diffs), the script targets just the two scalar fields by regex on
// the surrounding lines. The values are always `"N/M"` strings, so the
// pattern is tight.

function countDetectorFiles() {
  return readdirSync(SRC_DETECTORS).filter(
    (f) => f.endsWith('.ts') && f !== 'index.ts',
  ).length;
}

function rewriteDetectorCount(jsonPath, count) {
  const original = readFileSync(jsonPath, 'utf8');
  const want = `"${count}/${count}"`;
  // Two replacements anchored to the parent key — `target.detectors`
  // and `current.detectors`. `[\s\S]*?` is lazy so it captures the
  // shortest run from the parent's `{` to the first `"detectors":`
  // inside it. Any future `"detectors":` key under a different parent
  // (e.g. a hypothetical `stages.detectors`) is untouched because the
  // match anchor still requires `"target"` or `"current"`.
  let updated = original.replace(
    /("target":\s*\{[\s\S]*?"detectors":\s*)"\d+\/\d+"/,
    `$1${want}`,
  );
  updated = updated.replace(
    /("current":\s*\{[\s\S]*?"detectors":\s*)"\d+\/\d+"/,
    `$1${want}`,
  );
  if (updated === original) return {changed: false, count};
  writeFileSync(jsonPath, updated);
  return {changed: true, count};
}

const detectorCount = countDetectorFiles();
const claudeResult = rewriteDetectorCount(CLAUDE_PLUGIN_JSON, detectorCount);
if (claudeResult.changed) {
  console.log(
    `cladding plugin · detectors: recomputed → ${detectorCount}/${detectorCount} (updated ${CLAUDE_PLUGIN_JSON})`,
  );
} else {
  console.log(
    `cladding plugin · detectors: ${detectorCount}/${detectorCount} (already in sync)`,
  );
}
