// Cladding · plugin asset builder (v0.3.1 → v0.4.x, F-076 · F-077 · F-081).
//
// Single source of truth: src/agents/*.md (personas) + skills/*/SKILL.md
// (verbs). This script generates the host-specific plugin layouts:
//
//   Claude Code (plugins/claude-code/, v0.4.0):
//     agents/<id>.md       ← src/agents/<id>.md (verbatim copy)
//     commands/init.md     ← skills/init/SKILL.md (single user-facing verb)
//     .claude-plugin/plugin.json — declares mcpServers.cladding (canonical
//       MCP server declaration; replaces the v0.3.x repo-root `.mcp.json`).
//
//   Codex (plugins/codex/, v0.3.2, F-077):
//     skills/<verb>/SKILL.md   ← copied from repo-root skills/<verb>/SKILL.md
//     skills/<persona>/SKILL.md ← src/agents/<persona>.md re-wrapped as SKILL.md
//     .mcp.json             ← already authored under plugins/codex/
//     .codex-plugin/plugin.json ← already authored
//
//   Gemini CLI (plugins/gemini-cli/, v0.3.6, F-081):
//     commands/<verb>.toml ← transpiled from repo-root skills/<verb>/SKILL.md
//                            (frontmatter.description → toml `description`,
//                             body → toml `prompt` as a literal multi-line)
//     gemini-extension.json + GEMINI.md already authored.
//
// The src side stays canonical — every loadPersona() call in the
// runtime reads from src/agents. The drift detector enforces lockstep.
//
// Run: `npm run build:plugin` or as part of `npm run build`.

import {copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';

import {parse as parseYaml} from 'yaml';

const SRC_AGENTS = 'src/agents';
const SRC_SKILLS = 'skills';
const SRC_DETECTORS = 'src/stages/detectors';
const CLAUDE_PLUGIN_DIR = 'plugins/claude-code';
const CLAUDE_PLUGIN_JSON = `${CLAUDE_PLUGIN_DIR}/.claude-plugin/plugin.json`;

// --- Phase A — Claude Code mirror (plugins/claude-code/agents/) -------

const CLAUDE_AGENTS = `${CLAUDE_PLUGIN_DIR}/agents`;
mkdirSync(CLAUDE_AGENTS, {recursive: true});

const claudeGenerated = [];
for (const entry of readdirSync(SRC_AGENTS)) {
  if (!entry.endsWith('.md')) continue;
  if (entry === 'README.md') continue;
  const src = join(SRC_AGENTS, entry);
  if (!statSync(src).isFile()) continue;
  copyFileSync(src, join(CLAUDE_AGENTS, entry));
  claudeGenerated.push(entry);
}
writeFileSync(
  join(CLAUDE_AGENTS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs — do not edit. -->\n' +
    '<!-- Edit src/agents/<id>.md (the canonical source) instead. -->\n' +
    '\n' +
    '# Cladding plugin · agents/\n' +
    '\n' +
    'This directory is the Claude Code plugin manifest mirror of `src/agents/`.\n' +
    'Files here are copied verbatim from `src/agents/` by\n' +
    '`scripts/build-plugin.mjs` (run by `npm run build:plugin`).\n' +
    '\n' +
    'Edit the source under `src/agents/<id>.md`, then re-run the build.\n',
);
console.log(`cladding plugin · claude-code: copied ${claudeGenerated.length} agents → ${CLAUDE_AGENTS}/`);

// v0.4.0 (F-80d19d): Claude Code commands = `init` only (user-facing slash).
// Other verbs are invoked by the AI via natural language → `clad <verb>` CLI;
// keeping them out of the slash auto-complete keeps the namespace clean.
const CLAUDE_COMMANDS = `${CLAUDE_PLUGIN_DIR}/commands`;
mkdirSync(CLAUDE_COMMANDS, {recursive: true});
const initSkill = join(SRC_SKILLS, 'init', 'SKILL.md');
try {
  statSync(initSkill);
  copyFileSync(initSkill, join(CLAUDE_COMMANDS, 'init.md'));
  // Sweep stale per-verb commands from earlier builds (verb.md files and the
  // legacy clad.md wrapper).
  for (const file of readdirSync(CLAUDE_COMMANDS)) {
    if (file === 'init.md') continue;
    if (!file.endsWith('.md')) continue;
    rmSync(join(CLAUDE_COMMANDS, file));
  }
  console.log(`cladding plugin · claude-code: generated init slash command → ${CLAUDE_COMMANDS}/init.md`);
} catch {
  // skills/init/SKILL.md missing — leave the commands dir untouched and log
  // a warning so the build still completes for partial source trees.
  console.warn(`cladding plugin · claude-code: ${initSkill} not found — slash command skipped`);
}

// --- Phase B — Codex mirror (plugins/codex/skills/) -------------------

const CODEX_SKILLS = 'plugins/codex/skills';
mkdirSync(CODEX_SKILLS, {recursive: true});

// 1) verb skills — copied verbatim from repo-root `skills/<verb>/SKILL.md`
let codexVerbCount = 0;
for (const verb of readdirSync(SRC_SKILLS)) {
  const srcDir = join(SRC_SKILLS, verb);
  if (!statSync(srcDir).isDirectory()) continue;
  const srcFile = join(srcDir, 'SKILL.md');
  try {
    statSync(srcFile);
  } catch {
    continue;
  }
  const dstDir = join(CODEX_SKILLS, verb);
  mkdirSync(dstDir, {recursive: true});
  copyFileSync(srcFile, join(dstDir, 'SKILL.md'));
  codexVerbCount++;
}

// 2) persona skills — re-wrap src/agents/<id>.md as Codex SKILL.md
// The persona files already use YAML frontmatter with name + description
// + tools + capabilities; Codex's SKILL.md spec accepts arbitrary
// frontmatter and only requires `description`. The verbatim copy
// satisfies that — no transformation needed for v0.3.2.
let codexPersonaCount = 0;
for (const entry of readdirSync(SRC_AGENTS)) {
  if (!entry.endsWith('.md')) continue;
  if (entry === 'README.md') continue;
  const src = join(SRC_AGENTS, entry);
  if (!statSync(src).isFile()) continue;
  const personaId = entry.replace(/\.md$/, '');
  const dstDir = join(CODEX_SKILLS, personaId);
  mkdirSync(dstDir, {recursive: true});
  // Read + re-emit so we can confirm the YAML frontmatter has a
  // `description` field (Codex requires it). For v0.3.2 we trust the
  // src/agents files; if a future agent lacks description, the build
  // logs a warning and copies anyway.
  const content = readFileSync(src, 'utf8');
  if (!/^---\n[\s\S]*?\ndescription:/m.test(content)) {
    console.warn(`cladding plugin · codex: ${entry} lacks 'description' frontmatter — Codex may reject the skill.`);
  }
  writeFileSync(join(dstDir, 'SKILL.md'), content);
  codexPersonaCount++;
}

writeFileSync(
  join(CODEX_SKILLS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs — do not edit. -->\n' +
    '<!-- Edit src/agents/<id>.md or skills/<verb>/SKILL.md instead. -->\n' +
    '\n' +
    '# Cladding Codex plugin · skills/\n' +
    '\n' +
    'This directory is the Codex plugin manifest mirror, generated from\n' +
    'two canonical sources by `scripts/build-plugin.mjs`:\n' +
    '\n' +
    '- `<verb>/SKILL.md` ← copied verbatim from repo-root `skills/<verb>/SKILL.md`\n' +
    '- `<persona>/SKILL.md` ← copied verbatim from `src/agents/<persona>.md`\n' +
    '\n' +
    'Re-run `npm run build:plugin` after editing either source.\n',
);
console.log(
  `cladding plugin · codex: copied ${codexVerbCount} verbs + ${codexPersonaCount} personas → ${CODEX_SKILLS}/`,
);

// --- Phase C — Gemini CLI mirror (plugins/gemini-cli/commands/) -------

const GEMINI_COMMANDS = 'plugins/gemini-cli/commands';
mkdirSync(GEMINI_COMMANDS, {recursive: true});

/**
 * Splits a SKILL.md into its YAML frontmatter object and the body.
 * Returns null when no frontmatter delimiter is present so the
 * caller can decide whether to warn or skip.
 */
function splitFrontmatter(raw) {
  if (!raw.startsWith('---\n')) return null;
  const end = raw.indexOf('\n---\n', 4);
  if (end === -1) return null;
  const yamlText = raw.slice(4, end);
  const body = raw.slice(end + 5);
  return {frontmatter: parseYaml(yamlText) ?? {}, body};
}

/**
 * Escapes a string for TOML basic-string syntax (`"..."`).
 * - `\` → `\\`
 * - `"` → `\"`
 * Apostrophes pass through. Control chars are NOT scrubbed; cladding
 * skill descriptions are author-controlled prose and never contain
 * them in practice.
 */
function escapeTomlBasic(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/**
 * Renders a SKILL.md description + body into a TOML file Gemini CLI
 * accepts. Strategy:
 * - `description = "<escaped-basic-string>"` — single-line value.
 * - `prompt = '''<literal-multi-line>'''` — literal multi-line so
 *   backticks, backslashes, and other markdown punctuation pass
 *   through unaltered. The only escape concern is `'''` inside the
 *   body itself; we detect that case and fall back to the basic
 *   multi-line form (`"""..."""`) with appropriate escapes.
 */
function renderToml(description, body) {
  const desc = `description = "${escapeTomlBasic(description)}"`;
  if (!body.includes("'''")) {
    // Trim trailing whitespace but keep a leading newline for
    // readability — the closing `'''` lands on its own line.
    const trimmed = body.replace(/\s+$/, '');
    return `${desc}\nprompt = '''\n${trimmed}\n'''\n`;
  }
  // Fallback: body contains the literal sequence ' x 3, so use the
  // basic multi-line form and escape backslashes + double quotes.
  const escaped = body.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\s+$/, '');
  return `${desc}\nprompt = """\n${escaped}\n"""\n`;
}

// v0.4.0 (F-80d19d): slash command 노출 = `init` 만. 다른 verb 는 AI 가
// 자연어로 인식해 `clad <verb>` CLI 를 직접 호출하므로 사용자가 slash
// auto-complete 에서 직접 볼 필요 없음. Codex skills 는 AI 자동 invoke
// 라 12 verb 유지 (Phase B 그대로).
const USER_FACING_VERBS = new Set(['init']);

let geminiVerbCount = 0;
const geminiWarnings = [];
for (const verb of readdirSync(SRC_SKILLS)) {
  if (!USER_FACING_VERBS.has(verb)) continue;
  const srcDir = join(SRC_SKILLS, verb);
  if (!statSync(srcDir).isDirectory()) continue;
  const srcFile = join(srcDir, 'SKILL.md');
  try {
    statSync(srcFile);
  } catch {
    continue;
  }
  const raw = readFileSync(srcFile, 'utf8');
  const split = splitFrontmatter(raw);
  if (!split) {
    geminiWarnings.push(`${srcFile}: no YAML frontmatter — skipped`);
    continue;
  }
  const description = String(split.frontmatter.description ?? '').trim();
  if (!description) {
    geminiWarnings.push(`${srcFile}: frontmatter has no description field — skipped`);
    continue;
  }
  const body = split.body.trimStart();
  const toml = renderToml(description, body);
  writeFileSync(join(GEMINI_COMMANDS, `${verb}.toml`), toml);
  geminiVerbCount++;
}

// Clean up any stale verb .toml files from earlier builds (when all 12 verbs
// were emitted). Only the verbs in USER_FACING_VERBS should remain.
for (const file of readdirSync(GEMINI_COMMANDS)) {
  if (!file.endsWith('.toml')) continue;
  const verb = file.replace(/\.toml$/, '');
  if (USER_FACING_VERBS.has(verb)) continue;
  rmSync(join(GEMINI_COMMANDS, file));
}

// AUTO-GENERATED sentinel — same pattern the Claude Code mirror uses.
writeFileSync(
  join(GEMINI_COMMANDS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs — do not edit. -->\n' +
    '<!-- Edit skills/<verb>/SKILL.md (the canonical source) instead. -->\n' +
    '\n' +
    '# Cladding Gemini CLI plugin · commands/\n' +
    '\n' +
    'This directory is the Gemini CLI plugin manifest mirror, generated\n' +
    'by `scripts/build-plugin.mjs` from `skills/<verb>/SKILL.md`:\n' +
    '\n' +
    '- `description` ← SKILL.md frontmatter `description`\n' +
    '- `prompt` ← SKILL.md body (after frontmatter)\n' +
    '\n' +
    'TOML output uses literal multi-line strings (`\'\'\'…\'\'\'`) so\n' +
    'backticks and backslashes pass through unaltered.\n' +
    '\n' +
    'Re-run `npm run build:plugin` after editing the source.\n',
);

for (const w of geminiWarnings) {
  console.warn(`cladding plugin · gemini-cli: WARN ${w}`);
}
console.log(`cladding plugin · gemini-cli: transpiled ${geminiVerbCount} verbs → ${GEMINI_COMMANDS}/`);

// --- Phase D — Detector count auto-recompute (v0.3.17, F-092) ---------
//
// HARNESS_INTEGRITY detects drift between the count of non-index files
// under src/stages/detectors/ and the `N/M` value declared in
// .claude-plugin/plugin.json `ironclad.current.detectors` (and `.target`).
// Two concurrent branches each adding +1 detector merge cleanly on the
// file side but silently leave `(N+1)/(N+1)` instead of `(N+2)/(N+2)`
// because manual edits don't compose.
//
// This phase recomputes the count from the filesystem (the single
// source of truth) and rewrites both `current.detectors` and
// `target.detectors`. The build is idempotent — re-running with no
// changes produces no diff.
//
// Rewriting preserves byte layout: rather than parsing + reserializing
// the JSON (which would normalize formatting and produce nuisance
// diffs), the script targets just the two scalar fields by regex on
// the surrounding lines. The values are always `"N/M"` strings, so the
// pattern is tight.

function countDetectorFiles() {
  return readdirSync(SRC_DETECTORS).filter(
    (f) => f.endsWith('.ts') && f !== 'index.ts',
  ).length;
}

function rewriteDetectorCount(jsonPath, count) {
  const original = readFileSync(jsonPath, 'utf8');
  const want = `"${count}/${count}"`;
  // Two replacements anchored to the parent key — `target.detectors`
  // and `current.detectors`. `[\s\S]*?` is lazy so it captures the
  // shortest run from the parent's `{` to the first `"detectors":`
  // inside it. Any future `"detectors":` key under a different parent
  // (e.g. a hypothetical `stages.detectors`) is untouched because the
  // match anchor still requires `"target"` or `"current"`.
  let updated = original.replace(
    /("target":\s*\{[\s\S]*?"detectors":\s*)"\d+\/\d+"/,
    `$1${want}`,
  );
  updated = updated.replace(
    /("current":\s*\{[\s\S]*?"detectors":\s*)"\d+\/\d+"/,
    `$1${want}`,
  );
  if (updated === original) return {changed: false, count};
  writeFileSync(jsonPath, updated);
  return {changed: true, count};
}

const detectorCount = countDetectorFiles();
const claudeResult = rewriteDetectorCount(CLAUDE_PLUGIN_JSON, detectorCount);
if (claudeResult.changed) {
  console.log(
    `cladding plugin · detectors: recomputed → ${detectorCount}/${detectorCount} (updated ${CLAUDE_PLUGIN_JSON})`,
  );
} else {
  console.log(
    `cladding plugin · detectors: ${detectorCount}/${detectorCount} (already in sync)`,
  );
}

// --- Phase E — 4-host sub-agent transpile (0.4.10 PR-A.3) -------------
//
// Single canonical persona spec (src/agents/*.md) → each host's native
// sub-agent manifest format. The four hosts diverge in syntax:
//   - Claude Code: .md frontmatter (already mirrored in Phase A);
//     PR-A.3 also adds plugin.json `agents[]` array for the loader.
//   - Codex CLI: TOML (`.codex/agents/<id>.toml`); fields:
//     name / description / developer_instructions / model / sandbox_mode.
//   - Cursor IDE: single JSON file (`modes.json`) with mode array;
//     fields: name / model / tools / instructions.
//   - Gemini CLI: .md frontmatter (Claude Code lookalike); fields:
//     name / description / model / tools / allowed_tools.
//
// All four read hostHints from the canonical frontmatter (PR-A.2). Field
// mapping is intentional — keeps the per-host emitter pure-data so the
// transpile is testable in isolation.

/**
 * Parses a persona .md file into {id, frontmatter, body}. Re-implements
 * the small subset of loader.ts needed at build time (loader is TS;
 * this script is .mjs and runs at npm pack time without compilation).
 */
function parsePersonaFile(src) {
  const raw = readFileSync(src, 'utf8');
  if (!raw.startsWith('---\n')) return null;
  const end = raw.indexOf('\n---\n', 4);
  if (end === -1) return null;
  const yamlText = raw.slice(4, end);
  const body = raw.slice(end + 5).trim();
  const frontmatter = parseYaml(yamlText) ?? {};
  return {frontmatter, body};
}

/**
 * Returns the canonical persona list as [{id, frontmatter, body}].
 * Used by every Phase-E emitter so persona discovery is centralised.
 */
function loadAllPersonas() {
  const out = [];
  for (const entry of readdirSync(SRC_AGENTS)) {
    if (!entry.endsWith('.md')) continue;
    if (entry === 'README.md') continue;
    const src = join(SRC_AGENTS, entry);
    if (!statSync(src).isFile()) continue;
    const id = entry.replace(/\.md$/, '');
    const parsed = parsePersonaFile(src);
    if (!parsed) continue;
    out.push({id, ...parsed});
  }
  return out;
}

const ALL_PERSONAS = loadAllPersonas();

// E.1 — Claude Code: plugin.json `agents[]` declaration.
// Plugin manifest references the .md files already emitted by Phase A.
// Format follows the Claude Code 2026 plugin spec: each entry is
// {name, path}; the loader resolves path relative to the plugin root.
function rewriteClaudeAgentsArray(jsonPath, personas) {
  const original = readFileSync(jsonPath, 'utf8');
  const arrayLines = personas.map((p) => `    {"name": "${p.id}", "path": "./agents/${p.id}.md"}`);
  const want = `"agents": [\n${arrayLines.join(',\n')}\n  ]`;
  // Anchor to the line that already declares "hooks": "./hooks/hooks.json"
  // (added in 0.4.7 PR #170). Insert agents[] after it. Idempotent: if
  // an existing agents[] array is present, replace it.
  if (/"agents":\s*\[[\s\S]*?\]/.test(original)) {
    const updated = original.replace(/"agents":\s*\[[\s\S]*?\]/, want);
    if (updated === original) return {changed: false};
    writeFileSync(jsonPath, updated);
    return {changed: true};
  }
  // Insert after the `hooks` line.
  const hookMatch = original.match(/("hooks":\s*"\.\/hooks\/hooks\.json",?)/);
  if (!hookMatch) {
    // No hooks line — graceful no-op (Claude Code plugin manifest layout changed).
    return {changed: false};
  }
  const insertion = `${hookMatch[1]}\n  ${want},`;
  const updated = original.replace(hookMatch[1], insertion);
  if (updated === original) return {changed: false};
  writeFileSync(jsonPath, updated);
  return {changed: true};
}

const claudeAgentsResult = rewriteClaudeAgentsArray(CLAUDE_PLUGIN_JSON, ALL_PERSONAS);
console.log(
  `cladding plugin · claude-code: agents[] in plugin.json — ${
    claudeAgentsResult.changed ? 'updated' : 'already in sync'
  } (${ALL_PERSONAS.length} entries)`,
);

// E.2 — Codex CLI: .codex/agents/<id>.toml.
// Codex sub-agent TOML expects: name, description, developer_instructions,
// model (optional), sandbox_mode (optional). The body of the .md becomes
// developer_instructions (multi-line literal).
function escapeTomlBasicE2(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function renderCodexAgentToml(persona) {
  const hints = persona.frontmatter ?? {};
  const name = String(hints.name ?? persona.id);
  const description = String(hints.description ?? '');
  const lines = [
    `name = "${escapeTomlBasicE2(name)}"`,
    `description = "${escapeTomlBasicE2(description)}"`,
  ];
  if (hints.model) lines.push(`model = "${escapeTomlBasicE2(hints.model)}"`);
  if (hints.sandbox_mode) lines.push(`sandbox_mode = "${escapeTomlBasicE2(hints.sandbox_mode)}"`);
  if (typeof hints.maxTurns === 'number') lines.push(`max_turns = ${Math.floor(hints.maxTurns)}`);
  // developer_instructions as literal triple-quoted multi-line.
  const body = persona.body.replace(/\s+$/, '');
  if (body.includes("'''")) {
    // Fallback to basic multi-line with escaping.
    const escaped = body.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    lines.push(`developer_instructions = """\n${escaped}\n"""`);
  } else {
    lines.push(`developer_instructions = '''\n${body}\n'''`);
  }
  return lines.join('\n') + '\n';
}

const CODEX_AGENTS = 'plugins/codex/agents';
mkdirSync(CODEX_AGENTS, {recursive: true});
let codexAgentCount = 0;
for (const persona of ALL_PERSONAS) {
  const toml = renderCodexAgentToml(persona);
  writeFileSync(join(CODEX_AGENTS, `${persona.id}.toml`), toml);
  codexAgentCount++;
}
writeFileSync(
  join(CODEX_AGENTS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs Phase E — do not edit. -->\n' +
    '<!-- Canonical source: src/agents/<id>.md. -->\n' +
    '\n' +
    '# Cladding Codex plugin · agents/ (sub-agent TOML)\n' +
    '\n' +
    'Generated from `src/agents/<id>.md` by Phase E of build-plugin.mjs.\n' +
    'Codex sub-agent TOML schema (2026): `name`, `description`,\n' +
    '`developer_instructions`, optional `model` / `sandbox_mode` /\n' +
    '`max_turns`.\n',
);
console.log(`cladding plugin · codex: emitted ${codexAgentCount} sub-agent TOML → ${CODEX_AGENTS}/`);

// E.3 — Cursor IDE: single modes.json file (Custom Modes 2026).
// Cursor mode object: {name, model, tools, instructions}. The Cursor
// frontmatter `tools` enum overlaps with Claude Code's, so we pass it
// through verbatim.
function renderCursorModes(personas) {
  const modes = personas.map((p) => {
    const fm = p.frontmatter ?? {};
    const mode = {
      name: String(fm.name ?? p.id),
      description: String(fm.description ?? ''),
      instructions: p.body,
    };
    if (fm.model) mode.model = String(fm.model);
    if (fm.tools) mode.tools = String(fm.tools).split(',').map((t) => t.trim()).filter(Boolean);
    if (typeof fm.maxTurns === 'number') mode.max_turns = Math.floor(fm.maxTurns);
    return mode;
  });
  return JSON.stringify({version: 1, modes}, null, 2) + '\n';
}

const CURSOR_DIR = 'plugins/cursor';
const CURSOR_MODES_JSON = join(CURSOR_DIR, 'modes.json');
mkdirSync(CURSOR_DIR, {recursive: true});
const cursorModesBody = renderCursorModes(ALL_PERSONAS);
let cursorChanged = true;
try {
  const existing = readFileSync(CURSOR_MODES_JSON, 'utf8');
  if (existing === cursorModesBody) cursorChanged = false;
} catch {
  // file absent — write new
}
if (cursorChanged) writeFileSync(CURSOR_MODES_JSON, cursorModesBody);
console.log(
  `cladding plugin · cursor: emitted modes.json — ${
    cursorChanged ? 'updated' : 'already in sync'
  } (${ALL_PERSONAS.length} modes)`,
);

// E.4 — Gemini CLI: .gemini/agents/<id>.md (Claude Code lookalike).
// Gemini frontmatter is YAML, almost identical to Claude Code.
// We strip Claude-Code-specific fields (permissionMode, isolation are
// CC-specific) and emit a Gemini-friendly subset.
function renderGeminiAgent(persona) {
  const fm = persona.frontmatter ?? {};
  const lines = ['---'];
  lines.push(`name: ${fm.name ?? persona.id}`);
  if (fm.description) lines.push(`description: ${fm.description}`);
  if (fm.model) lines.push(`model: ${fm.model}`);
  // Gemini uses `allowed_tools` (snake_case) instead of `tools`.
  if (fm.tools) {
    const toolList = String(fm.tools).split(',').map((t) => t.trim()).filter(Boolean);
    lines.push(`allowed_tools:\n${toolList.map((t) => `  - ${t}`).join('\n')}`);
  }
  if (typeof fm.maxTurns === 'number') lines.push(`max_turns: ${Math.floor(fm.maxTurns)}`);
  lines.push('---');
  lines.push('');
  lines.push(persona.body);
  lines.push('');
  return lines.join('\n');
}

const GEMINI_AGENTS = 'plugins/gemini-cli/agents';
mkdirSync(GEMINI_AGENTS, {recursive: true});
let geminiAgentCount = 0;
for (const persona of ALL_PERSONAS) {
  const md = renderGeminiAgent(persona);
  writeFileSync(join(GEMINI_AGENTS, `${persona.id}.md`), md);
  geminiAgentCount++;
}
writeFileSync(
  join(GEMINI_AGENTS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs Phase E — do not edit. -->\n' +
    '<!-- Canonical source: src/agents/<id>.md. -->\n' +
    '\n' +
    '# Cladding Gemini CLI plugin · agents/ (sub-agent .md)\n' +
    '\n' +
    'Generated from `src/agents/<id>.md` by Phase E of build-plugin.mjs.\n' +
    'Gemini sub-agent .md schema (2026, Apr release): YAML frontmatter\n' +
    'with `name` / `description` / `model` / `allowed_tools` /\n' +
    '`max_turns`. Drops Claude-Code-specific fields (permissionMode,\n' +
    'isolation, sandbox_mode).\n',
);
console.log(
  `cladding plugin · gemini-cli: emitted ${geminiAgentCount} sub-agent .md → ${GEMINI_AGENTS}/`,
);
