// Cladding · plugin asset builder (v0.3.1, F-076).
//
// Mirrors `src/agents/*.md` (the cladding-internal persona SSoT) into
// `agents/*.md` at the repo root so Claude Code's plugin loader finds
// them in the expected layout. The src side stays canonical — every
// loadPersona() call in the runtime reads from src/agents. This
// script is the one-way copier; the drift detector enforces lockstep.
//
// Run: `npm run build:plugin` or as part of `npm run build`.

import {copyFileSync, mkdirSync, readdirSync, statSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';

const SRC = 'src/agents';
const DST = 'agents';

mkdirSync(DST, {recursive: true});

const generated = [];
for (const entry of readdirSync(SRC)) {
  if (!entry.endsWith('.md')) continue;
  if (entry === 'README.md') continue;
  const src = join(SRC, entry);
  if (!statSync(src).isFile()) continue;
  const dst = join(DST, entry);
  copyFileSync(src, dst);
  generated.push(entry);
}

// Write a sentinel so a human reading the directory understands it's
// a build artifact, not a source file. The sentinel ALSO acts as a
// drift anchor — if someone edits agents/<id>.md by hand the next
// build overwrites them.
writeFileSync(
  join(DST, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs — do not edit. -->\n' +
    '<!-- Edit src/agents/<id>.md (the canonical source) instead. -->\n' +
    '\n' +
    '# Cladding plugin · agents/\n' +
    '\n' +
    'This directory is the Claude Code plugin manifest mirror of `src/agents/`.\n' +
    'Files here are copied verbatim from `src/agents/` by\n' +
    '`scripts/build-plugin.mjs` (run by `npm run build:plugin`).\n' +
    '\n' +
    'Edit the source under `src/agents/<id>.md`, then re-run the build.\n',
);

console.log(`cladding plugin: copied ${generated.length} agents → ${DST}/`);
