// Cladding · scenarios · ab · report (v0.3.47, F-4db939)
//
// Deterministic markdown generation from A/B snapshots. The same
// snapshot inputs always produce the same markdown — committed
// reports live under docs/ab-evaluation/ and act as a snapshot test.
// A regression that changes the metric numbers will diff against the
// committed report and fail the test, forcing reviewer attention.

import {readFileSync, writeFileSync, existsSync, mkdirSync} from 'node:fs';
import {dirname} from 'node:path';

import {diffToRows, type AbSnapshot} from './_ab-metrics.js';

/** Case report top-level options. */
export interface CaseReportInput {
  readonly caseTitle: string;
  readonly intent: string;
  readonly description: string;
  readonly hypothesisFocus: readonly string[];
  readonly m1A: AbSnapshot;
  readonly m1B: AbSnapshot;
  readonly m2A: AbSnapshot;
  readonly m2B: AbSnapshot;
}

export function renderCaseReport(input: CaseReportInput): string {
  const lines: string[] = [];
  lines.push(
    `<!-- Cladding · ab-evaluation · ${input.caseTitle} · auto-generated by tests/scenarios/ab/case-*.test.ts -->`,
  );
  lines.push('');
  lines.push(`# A/B Evaluation: ${input.caseTitle}`);
  lines.push('');
  lines.push(`**Intent:** \`${input.intent}\``);
  lines.push('');
  lines.push(input.description.trim());
  lines.push('');
  lines.push('## Hypotheses tested');
  lines.push('');
  for (const h of input.hypothesisFocus) lines.push(`- ${h}`);
  lines.push('');

  // M1
  lines.push('## M1 — Initial setup');
  lines.push('');
  lines.push(renderMilestoneTable(input.m1A, input.m1B));
  lines.push('');
  lines.push(renderDetectorBlock(input.m1A, input.m1B));
  lines.push('');

  // M2
  lines.push('## M2 — First feature complete');
  lines.push('');
  lines.push(renderMilestoneTable(input.m2A, input.m2B));
  lines.push('');
  lines.push(renderDetectorBlock(input.m2A, input.m2B));
  lines.push('');

  // Findings
  lines.push('## Findings');
  lines.push('');
  lines.push(renderFindings(input.m2A, input.m2B));
  lines.push('');

  // Replay
  lines.push('## How to reproduce');
  lines.push('');
  lines.push('```bash');
  lines.push(`npm test -- tests/scenarios/ab/case-${slugify(input.caseTitle)}.test.ts`);
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

function renderMilestoneTable(a: AbSnapshot, b: AbSnapshot): string {
  const rows = diffToRows(a, b);
  const out: string[] = [];
  out.push('| Metric | A (Cladding) | B (Vanilla) | Δ |');
  out.push('|---|---:|---:|---:|');
  for (const r of rows) {
    out.push(`| ${escapePipe(r.label)} | ${r.a} | ${r.b} | ${r.delta} |`);
  }
  return out.join('\n');
}

function renderDetectorBlock(a: AbSnapshot, b: AbSnapshot): string {
  const lines: string[] = [];
  lines.push('**Detector outcomes** (META_INTEGRITY + HARDCODED_SECRET excluded — toolchain-only checks):');
  lines.push('');
  lines.push('```');
  lines.push(`A (Cladding) — errors: ${a.crossDocConsistency.errors}  warns: ${a.crossDocConsistency.warnings}  infos: ${a.crossDocConsistency.infos}`);
  if (a.crossDocConsistency.errorSamples.length > 0) {
    lines.push('  Sample errors:');
    for (const s of a.crossDocConsistency.errorSamples) lines.push(`    - ${truncate(s, 140)}`);
  }
  lines.push('');
  lines.push(`B (Vanilla)  — errors: ${b.crossDocConsistency.errors}  warns: ${b.crossDocConsistency.warnings}  infos: ${b.crossDocConsistency.infos}`);
  if (b.crossDocConsistency.errorSamples.length > 0) {
    lines.push('  Sample errors:');
    for (const s of b.crossDocConsistency.errorSamples) lines.push(`    - ${truncate(s, 140)}`);
  }
  lines.push('```');
  return lines.join('\n');
}

function renderFindings(a: AbSnapshot, b: AbSnapshot): string {
  const lines: string[] = [];
  const tieredA =
    a.tieredArtifactCount.tierA + a.tieredArtifactCount.tierB + a.tieredArtifactCount.tierC + a.tieredArtifactCount.tierD;
  const tieredB =
    b.tieredArtifactCount.tierA + b.tieredArtifactCount.tierB + b.tieredArtifactCount.tierC + b.tieredArtifactCount.tierD;
  lines.push(
    `- **Structured artifacts**: cladding produces ${tieredA} tier-banner-bearing files vs vanilla's ${tieredB}.`,
  );
  lines.push(
    `- **Spec ↔ code traceability**: cladding emits ${a.specCompleteness.features} feature(s), ${a.specCompleteness.acceptanceCriteria} AC(s), ${a.specCompleteness.scenarios} scenario(s), ${a.specCompleteness.capabilities} capability(s); vanilla has 0 of each.`,
  );
  lines.push(
    `- **Architecture enforcement**: cladding declares ${a.layerCompliance.layersDeclared} layer(s) with ${a.layerCompliance.forbiddenImportRules} forbidden-import rule(s); vanilla has 0.`,
  );
  lines.push(
    `- **Detector behavior**: cladding-managed tree → ${a.crossDocConsistency.errors} error(s) / ${a.crossDocConsistency.warnings} warn(s) / ${a.crossDocConsistency.infos} info(s). Vanilla tree → ${b.crossDocConsistency.errors} / ${b.crossDocConsistency.warnings} / ${b.crossDocConsistency.infos}. The detectors that gate against spec (REFERENCE_INTEGRITY, MISSING_IMPLEMENTATION, ARCHITECTURE_FROM_SPEC, CAPABILITIES_FEATURE_MAPPING) need cladding's artifacts to evaluate — without them they silently pass. The "0 errors on vanilla" therefore is **absence of signal**, not absence of drift.`,
  );
  lines.push(
    `- **Token cost**: cladding's cumulative artifact + code consumes ~${a.tokenConsumption.estTokens} tokens vs vanilla's ~${b.tokenConsumption.estTokens} (heuristic chars/4) — Δ ≈ ${a.tokenConsumption.estTokens - b.tokenConsumption.estTokens} tokens, the price of structure.`,
  );
  lines.push(
    `- **Code surface**: vanilla writes ${b.codeStructure.sourceFiles} source file(s) / ${b.codeStructure.totalSourceLoc} LoC + ${b.codeStructure.testFiles} test file(s) / ${b.testCoverage.testCases} test case(s); cladding writes ${a.codeStructure.sourceFiles} / ${a.codeStructure.totalSourceLoc} + ${a.codeStructure.testFiles} / ${a.testCoverage.testCases}. (Vanilla front-loads code, cladding front-loads spec — both converge by M2.)`,
  );
  return lines.join('\n');
}

function escapePipe(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function truncate(s: string, max: number): string {
  return s.length > max ? `${s.slice(0, max - 1)}…` : s;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// ──────────────────────────────────────────────────────────────────
// Snapshot file gate
//
// Case tests call `writeOrAssertReport(reportAbsPath, generated)`:
//   - When `UPDATE_AB_REPORTS=1` env var is set, the file is
//     (re)written so the developer can intentionally update it.
//   - Otherwise the existing file's content is compared to the
//     generated content. Diff → throw → vitest failure.
// This is the standard committed-snapshot pattern. CI keeps the
// committed report deterministic; local devs can refresh with the
// env var when metrics shift legitimately.
// ──────────────────────────────────────────────────────────────────

export function writeOrAssertReport(reportAbsPath: string, generated: string): void {
  const shouldUpdate = process.env.UPDATE_AB_REPORTS === '1';
  if (shouldUpdate) {
    mkdirSync(dirname(reportAbsPath), {recursive: true});
    writeFileSync(reportAbsPath, generated);
    return;
  }
  if (!existsSync(reportAbsPath)) {
    throw new Error(
      `writeOrAssertReport: ${reportAbsPath} does not exist. Run with UPDATE_AB_REPORTS=1 to create it.`,
    );
  }
  const onDisk = readFileSync(reportAbsPath, 'utf8');
  if (onDisk !== generated) {
    throw new Error(
      `writeOrAssertReport: ${reportAbsPath} content drift. ` +
        'Re-run with UPDATE_AB_REPORTS=1 if the metric changes are intentional. ' +
        `First diff:\n${firstDiff(onDisk, generated)}`,
    );
  }
}

function firstDiff(a: string, b: string): string {
  const al = a.split('\n');
  const bl = b.split('\n');
  for (let i = 0; i < Math.max(al.length, bl.length); i++) {
    if (al[i] !== bl[i]) {
      return `  L${i + 1} on-disk: ${(al[i] ?? '<EOF>').slice(0, 120)}\n  L${i + 1} generated: ${(bl[i] ?? '<EOF>').slice(0, 120)}`;
    }
  }
  return '  (no line diff — content lengths differ in trailing newline)';
}
